//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsRFBReginV2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9080/services/ws01")]
        public string WsRFBReginV2_WsServices01RFB_WS01Service {
            get {
                return ((string)(this["WsRFBReginV2_WsServices01RFB_WS01Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wwwc.webhom.serpro.gov.br:443/services/ws04/ws04")]
        public string WsRFBReginV2_WsServices04RFB_ws04 {
            get {
                return ((string)(this["WsRFBReginV2_WsServices04RFB_ws04"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.webdes.serpro:80/services/ws05/ws05")]
        public string WsRFBReginV2_WsServices05RFB_WS05Service_serviceagent {
            get {
                return ((string)(this["WsRFBReginV2_WsServices05RFB_WS05Service_serviceagent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www14c.receita.fazenda.gov.br:443/services/ws06/ws06")]
        public string WsRFBReginV2_WsServices06RFB_WS06Service_serviceagent {
            get {
                return ((string)(this["WsRFBReginV2_WsServices06RFB_WS06Service_serviceagent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9080/services/ws07/ws07")]
        public string WsRFBReginV2_WsServices07RFB_ws07 {
            get {
                return ((string)(this["WsRFBReginV2_WsServices07RFB_ws07"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wwwc.webhom.serpro.gov.br:443/services/ws08/ws08")]
        public string WsRFBReginV2_WsServices08RFB_ws08 {
            get {
                return ((string)(this["WsRFBReginV2_WsServices08RFB_ws08"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://0.0.0.0:8080/services/ws09")]
        public string WsRFBReginV2_WsServices09RFB_WS09Service_serviceagent {
            get {
                return ((string)(this["WsRFBReginV2_WsServices09RFB_WS09Service_serviceagent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wwwc.webhom.serpro.gov.br:443/services/ws11/ws11")]
        public string WsRFBReginV2_WsServices11RFB_WS11Service_serviceagent {
            get {
                return ((string)(this["WsRFBReginV2_WsServices11RFB_WS11Service_serviceagent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wwwc.webhom.serpro.gov.br:443/services/ws13/ws13")]
        public string WsRFBReginV2_WsServices13RFB_ws13 {
            get {
                return ((string)(this["WsRFBReginV2_WsServices13RFB_ws13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9080/services/ws15/ws15")]
        public string WsRFBReginV2_WsServices15RFB_ws15 {
            get {
                return ((string)(this["WsRFBReginV2_WsServices15RFB_ws15"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wwwc.webhom.serpro.gov.br:443/services/ws23/ws23")]
        public string WsRFBReginV2_WsServices23RFB_ws23 {
            get {
                return ((string)(this["WsRFBReginV2_WsServices23RFB_ws23"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wwwc.webhom.serpro.gov.br:443/services/ws24/ws24")]
        public string WsRFBReginV2_WsServices24RFB_ws24 {
            get {
                return ((string)(this["WsRFBReginV2_WsServices24RFB_ws24"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9080/services/ws35/ws35")]
        public string WsRFBReginV2_WsServices35RFB_ws35 {
            get {
                return ((string)(this["WsRFBReginV2_WsServices35RFB_ws35"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9080/services/ws53/ws53")]
        public string WsRFBReginV2_WsServices53RFB_ws53 {
            get {
                return ((string)(this["WsRFBReginV2_WsServices53RFB_ws53"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://regin.juceb.ba.gov.br/wsrfbregin/ServiceReginRFB.asmx")]
        public string WsRFBReginV2_WsServicesReginRFB_ServiceReginRFB {
            get {
                return ((string)(this["WsRFBReginV2_WsServicesReginRFB_ServiceReginRFB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www14c.receita.fazenda.gov.br:443/services/ws22/ws22")]
        public string WsRFBReginV2_WsServices22RFB_WS22Service {
            get {
                return ((string)(this["WsRFBReginV2_WsServices22RFB_WS22Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9080/services/ws17/ws17")]
        public string WsRFBReginV2_WsServices17RFB_ws17 {
            get {
                return ((string)(this["WsRFBReginV2_WsServices17RFB_ws17"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9191/services/ws02")]
        public string WsRFBReginV2_WsServices02RFB_WS02Service {
            get {
                return ((string)(this["WsRFBReginV2_WsServices02RFB_WS02Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://homologappsre/SVC_IntegracaoReginTeste/SVC_IntegracaoRegin.asmx")]
        public string WsRFBReginV2_RJ_ServiceEnvS01_SVC_IntegracaoRegin {
            get {
                return ((string)(this["WsRFBReginV2_RJ_ServiceEnvS01_SVC_IntegracaoRegin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:4200/WsRFBRegin/ServicosConsultas.asmx")]
        public string WsRFBReginV2_WsServicosConsulta_ServicosConsultas {
            get {
                return ((string)(this["WsRFBReginV2_WsServicosConsulta_ServicosConsultas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom-lredesim.estaleiro.serpro.gov.br/s50/soap")]
        public string WsRFBReginV2_WsServices50RFB_S50PortService {
            get {
                return ((string)(this["WsRFBReginV2_WsServices50RFB_S50PortService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://homologappsre/SVC_IntegracaoReginTeste/SVC_IntegracaoRegin.asmx")]
        public string WsRFBReginV2_RJ_Servico_S99_SVC_IntegracaoRegin {
            get {
                return ((string)(this["WsRFBReginV2_RJ_Servico_S99_SVC_IntegracaoRegin"]));
            }
        }
    }
}
