//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsRFBReginV2.RJ_Servico_MEI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestMEI", Namespace="jucerja.rj.servicos.datacontract")]
    [System.SerializableAttribute()]
    public partial class RequestMEI : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CNPJField;
        
        private System.DateTime DataEventoMEIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataInclusaoCargaServico99Field;
        
        private string IdReginField;
        
        private string IndicadorAcaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WsRFBReginV2.RJ_Servico_MEI.RequestOficio OficioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WsRFBReginV2.RJ_Servico_MEI.RequestS35 S35Field;
        
        private string UFSolicitacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLRfbS11Field;
        
        private string XMLRfbS15Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string CNPJ {
            get {
                return this.CNPJField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPJField, value) != true)) {
                    this.CNPJField = value;
                    this.RaisePropertyChanged("CNPJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public System.DateTime DataEventoMEI {
            get {
                return this.DataEventoMEIField;
            }
            set {
                if ((this.DataEventoMEIField.Equals(value) != true)) {
                    this.DataEventoMEIField = value;
                    this.RaisePropertyChanged("DataEventoMEI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> DataInclusaoCargaServico99 {
            get {
                return this.DataInclusaoCargaServico99Field;
            }
            set {
                if ((this.DataInclusaoCargaServico99Field.Equals(value) != true)) {
                    this.DataInclusaoCargaServico99Field = value;
                    this.RaisePropertyChanged("DataInclusaoCargaServico99");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string IdRegin {
            get {
                return this.IdReginField;
            }
            set {
                if ((object.ReferenceEquals(this.IdReginField, value) != true)) {
                    this.IdReginField = value;
                    this.RaisePropertyChanged("IdRegin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string IndicadorAcao {
            get {
                return this.IndicadorAcaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IndicadorAcaoField, value) != true)) {
                    this.IndicadorAcaoField = value;
                    this.RaisePropertyChanged("IndicadorAcao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WsRFBReginV2.RJ_Servico_MEI.RequestOficio Oficio {
            get {
                return this.OficioField;
            }
            set {
                if ((object.ReferenceEquals(this.OficioField, value) != true)) {
                    this.OficioField = value;
                    this.RaisePropertyChanged("Oficio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WsRFBReginV2.RJ_Servico_MEI.RequestS35 S35 {
            get {
                return this.S35Field;
            }
            set {
                if ((object.ReferenceEquals(this.S35Field, value) != true)) {
                    this.S35Field = value;
                    this.RaisePropertyChanged("S35");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string UFSolicitacao {
            get {
                return this.UFSolicitacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.UFSolicitacaoField, value) != true)) {
                    this.UFSolicitacaoField = value;
                    this.RaisePropertyChanged("UFSolicitacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string XMLRfbS11 {
            get {
                return this.XMLRfbS11Field;
            }
            set {
                if ((object.ReferenceEquals(this.XMLRfbS11Field, value) != true)) {
                    this.XMLRfbS11Field = value;
                    this.RaisePropertyChanged("XMLRfbS11");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string XMLRfbS15 {
            get {
                return this.XMLRfbS15Field;
            }
            set {
                if ((object.ReferenceEquals(this.XMLRfbS15Field, value) != true)) {
                    this.XMLRfbS15Field = value;
                    this.RaisePropertyChanged("XMLRfbS15");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestOficio", Namespace="jucerja.rj.servicos.datacontract")]
    [System.SerializableAttribute()]
    public partial class RequestOficio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoConvenioAtoOficioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroAtoOficioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CodigoConvenioAtoOficio {
            get {
                return this.CodigoConvenioAtoOficioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoConvenioAtoOficioField, value) != true)) {
                    this.CodigoConvenioAtoOficioField = value;
                    this.RaisePropertyChanged("CodigoConvenioAtoOficio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NumeroAtoOficio {
            get {
                return this.NumeroAtoOficioField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroAtoOficioField, value) != true)) {
                    this.NumeroAtoOficioField = value;
                    this.RaisePropertyChanged("NumeroAtoOficio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestS35", Namespace="jucerja.rj.servicos.datacontract")]
    [System.SerializableAttribute()]
    public partial class RequestS35 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroIdentificacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroReciboField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NumeroIdentificacao {
            get {
                return this.NumeroIdentificacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroIdentificacaoField, value) != true)) {
                    this.NumeroIdentificacaoField = value;
                    this.RaisePropertyChanged("NumeroIdentificacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NumeroRecibo {
            get {
                return this.NumeroReciboField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroReciboField, value) != true)) {
                    this.NumeroReciboField = value;
                    this.RaisePropertyChanged("NumeroRecibo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMEI", Namespace="jucerja.rj.servicos.datacontract")]
    [System.SerializableAttribute()]
    public partial class ResponseMEI : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoField;
        
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Observacao {
            get {
                return this.ObservacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacaoField, value) != true)) {
                    this.ObservacaoField = value;
                    this.RaisePropertyChanged("Observacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://jucerja.rj.servicos", ConfigurationName="RJ_Servico_MEI.IServicoIntegracaoMEI")]
    public interface IServicoIntegracaoMEI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jucerja.rj.servicos/IServicoIntegracaoMEI/AtualizarMEI", ReplyAction="http://jucerja.rj.servicos/IServicoIntegracaoMEI/AtualizarMEIResponse")]
        WsRFBReginV2.RJ_Servico_MEI.ResponseMEI AtualizarMEI(WsRFBReginV2.RJ_Servico_MEI.RequestMEI request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jucerja.rj.servicos/IServicoIntegracaoMEI/AtualizarMEI", ReplyAction="http://jucerja.rj.servicos/IServicoIntegracaoMEI/AtualizarMEIResponse")]
        System.Threading.Tasks.Task<WsRFBReginV2.RJ_Servico_MEI.ResponseMEI> AtualizarMEIAsync(WsRFBReginV2.RJ_Servico_MEI.RequestMEI request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoIntegracaoMEIChannel : WsRFBReginV2.RJ_Servico_MEI.IServicoIntegracaoMEI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoIntegracaoMEIClient : System.ServiceModel.ClientBase<WsRFBReginV2.RJ_Servico_MEI.IServicoIntegracaoMEI>, WsRFBReginV2.RJ_Servico_MEI.IServicoIntegracaoMEI {
        
        public ServicoIntegracaoMEIClient() {
        }
        
        public ServicoIntegracaoMEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoIntegracaoMEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoIntegracaoMEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoIntegracaoMEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WsRFBReginV2.RJ_Servico_MEI.ResponseMEI AtualizarMEI(WsRFBReginV2.RJ_Servico_MEI.RequestMEI request) {
            return base.Channel.AtualizarMEI(request);
        }
        
        public System.Threading.Tasks.Task<WsRFBReginV2.RJ_Servico_MEI.ResponseMEI> AtualizarMEIAsync(WsRFBReginV2.RJ_Servico_MEI.RequestMEI request) {
            return base.Channel.AtualizarMEIAsync(request);
        }
    }
}
