//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WsRFBReginV2.WsServices11RFB {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS11HttpSoapBinding", Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class WS11Serviceserviceagent : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultaCNPJOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS11Serviceserviceagent() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::WsRFBReginV2.Properties.Settings.Default.WsRFBReginV2_WsServices11RFB_WS11Service_serviceagent;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultaCNPJCompletedEventHandler consultaCNPJCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("/ws11-service0.serviceagent/WS11Endpoint0/consultaCNPJ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultaCNPJResponse", Namespace="http://servicos.integrador.serpro.gov.br/")]
        public consultaCNPJResponse consultaCNPJ([System.Xml.Serialization.XmlElementAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")] consultaCNPJRequest consultaCNPJRequest) {
            object[] results = this.Invoke("consultaCNPJ", new object[] {
                        consultaCNPJRequest});
            return ((consultaCNPJResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultaCNPJAsync(consultaCNPJRequest consultaCNPJRequest) {
            this.consultaCNPJAsync(consultaCNPJRequest, null);
        }
        
        /// <remarks/>
        public void consultaCNPJAsync(consultaCNPJRequest consultaCNPJRequest, object userState) {
            if ((this.consultaCNPJOperationCompleted == null)) {
                this.consultaCNPJOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaCNPJOperationCompleted);
            }
            this.InvokeAsync("consultaCNPJ", new object[] {
                        consultaCNPJRequest}, this.consultaCNPJOperationCompleted, userState);
        }
        
        private void OnconsultaCNPJOperationCompleted(object arg) {
            if ((this.consultaCNPJCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaCNPJCompleted(this, new consultaCNPJCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class consultaCNPJRequest {
        
        private string codServicoField;
        
        private string versaoField;
        
        private string usoRFBField;
        
        private string numeroProtocoloField;
        
        private int numeroOcorrenciaField;
        
        private bool numeroOcorrenciaFieldSpecified;
        
        private string codEventoField;
        
        private string[] cnpjField;
        
        private string reciboSolicitacaoField;
        
        private string identificacaoSolicitacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codServico {
            get {
                return this.codServicoField;
            }
            set {
                this.codServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usoRFB {
            get {
                return this.usoRFBField;
            }
            set {
                this.usoRFBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroProtocolo {
            get {
                return this.numeroProtocoloField;
            }
            set {
                this.numeroProtocoloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numeroOcorrencia {
            get {
                return this.numeroOcorrenciaField;
            }
            set {
                this.numeroOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroOcorrenciaSpecified {
            get {
                return this.numeroOcorrenciaFieldSpecified;
            }
            set {
                this.numeroOcorrenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codEvento {
            get {
                return this.codEventoField;
            }
            set {
                this.codEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cnpj", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reciboSolicitacao {
            get {
                return this.reciboSolicitacaoField;
            }
            set {
                this.reciboSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacaoSolicitacao {
            get {
                return this.identificacaoSolicitacaoField;
            }
            set {
                this.identificacaoSolicitacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class dadosSocio {
        
        private string cpfCnpjField;
        
        private string nomeField;
        
        private string qualificacaoField;
        
        private string dataInclusaoField;
        
        private string valorPartCapitalSocialStringField;
        
        private string paisOrigemField;
        
        private string cpfRepresentanteLegalField;
        
        private string nomeRepresentanteLegalField;
        
        private string qualificacaoRepresentanteLegalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfCnpj {
            get {
                return this.cpfCnpjField;
            }
            set {
                this.cpfCnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string qualificacao {
            get {
                return this.qualificacaoField;
            }
            set {
                this.qualificacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataInclusao {
            get {
                return this.dataInclusaoField;
            }
            set {
                this.dataInclusaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valorPartCapitalSocialString {
            get {
                return this.valorPartCapitalSocialStringField;
            }
            set {
                this.valorPartCapitalSocialStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paisOrigem {
            get {
                return this.paisOrigemField;
            }
            set {
                this.paisOrigemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfRepresentanteLegal {
            get {
                return this.cpfRepresentanteLegalField;
            }
            set {
                this.cpfRepresentanteLegalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeRepresentanteLegal {
            get {
                return this.nomeRepresentanteLegalField;
            }
            set {
                this.nomeRepresentanteLegalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string qualificacaoRepresentanteLegal {
            get {
                return this.qualificacaoRepresentanteLegalField;
            }
            set {
                this.qualificacaoRepresentanteLegalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class endereco {
        
        private string indOrigemEnderecoField;
        
        private string cepField;
        
        private string ufField;
        
        private string codMunicipioField;
        
        private string codTipoLogradouroField;
        
        private string logradouroField;
        
        private string numLogradouroField;
        
        private string complementoLogradouroField;
        
        private string bairroField;
        
        private string distritoField;
        
        private string referenciaField;
        
        private string cidadeExteriorField;
        
        private string codPaisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indOrigemEndereco {
            get {
                return this.indOrigemEnderecoField;
            }
            set {
                this.indOrigemEnderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codMunicipio {
            get {
                return this.codMunicipioField;
            }
            set {
                this.codMunicipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoLogradouro {
            get {
                return this.codTipoLogradouroField;
            }
            set {
                this.codTipoLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numLogradouro {
            get {
                return this.numLogradouroField;
            }
            set {
                this.numLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string complementoLogradouro {
            get {
                return this.complementoLogradouroField;
            }
            set {
                this.complementoLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cidadeExterior {
            get {
                return this.cidadeExteriorField;
            }
            set {
                this.cidadeExteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPais {
            get {
                return this.codPaisField;
            }
            set {
                this.codPaisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class dadosCNPJ {
        
        private string cnpjField;
        
        private string nomeEmpresarialField;
        
        private string indMatrizFilialField;
        
        private string dataAberturaEstabelecimentoField;
        
        private string dataAberturaEmpresaField;
        
        private string situacaoCadastralField;
        
        private endereco enderecoField;
        
        private string objetoSocialField;
        
        private string naturezaJuridicaField;
        
        private string numeroOrgaoRegistroField;
        
        private string capitalSocialField;
        
        private string cpfRepresentanteField;
        
        private string nomeRepresentanteField;
        
        private string qualificacaoRepresentanteField;
        
        private string cpfPrepostoField;
        
        private string nomePrepostoField;
        
        private string porteField;
        
        private string opcaoSimplesNacionalField;
        
        private string opcaoSimeiField;
        
        private string cnaePrincipalField;
        
        private string[] cnaeSecundariaField;
        
        private string[] tipoUnidadeField;
        
        private string[] formaAtuacaoField;
        
        private string[] cnpjFilialField;
        
        private string[] ufFilialField;
        
        private string[] numeroRegistroFilialField;
        
        private string cnpjMatrizField;
        
        private string ufMatrizField;
        
        private string numeroRegistroMatrizField;
        
        private dadosSocio[] dadosSocioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeEmpresarial {
            get {
                return this.nomeEmpresarialField;
            }
            set {
                this.nomeEmpresarialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indMatrizFilial {
            get {
                return this.indMatrizFilialField;
            }
            set {
                this.indMatrizFilialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataAberturaEstabelecimento {
            get {
                return this.dataAberturaEstabelecimentoField;
            }
            set {
                this.dataAberturaEstabelecimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataAberturaEmpresa {
            get {
                return this.dataAberturaEmpresaField;
            }
            set {
                this.dataAberturaEmpresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string situacaoCadastral {
            get {
                return this.situacaoCadastralField;
            }
            set {
                this.situacaoCadastralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string objetoSocial {
            get {
                return this.objetoSocialField;
            }
            set {
                this.objetoSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string naturezaJuridica {
            get {
                return this.naturezaJuridicaField;
            }
            set {
                this.naturezaJuridicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroOrgaoRegistro {
            get {
                return this.numeroOrgaoRegistroField;
            }
            set {
                this.numeroOrgaoRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string capitalSocial {
            get {
                return this.capitalSocialField;
            }
            set {
                this.capitalSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfRepresentante {
            get {
                return this.cpfRepresentanteField;
            }
            set {
                this.cpfRepresentanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeRepresentante {
            get {
                return this.nomeRepresentanteField;
            }
            set {
                this.nomeRepresentanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string qualificacaoRepresentante {
            get {
                return this.qualificacaoRepresentanteField;
            }
            set {
                this.qualificacaoRepresentanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfPreposto {
            get {
                return this.cpfPrepostoField;
            }
            set {
                this.cpfPrepostoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomePreposto {
            get {
                return this.nomePrepostoField;
            }
            set {
                this.nomePrepostoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string porte {
            get {
                return this.porteField;
            }
            set {
                this.porteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string opcaoSimplesNacional {
            get {
                return this.opcaoSimplesNacionalField;
            }
            set {
                this.opcaoSimplesNacionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string opcaoSimei {
            get {
                return this.opcaoSimeiField;
            }
            set {
                this.opcaoSimeiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnaePrincipal {
            get {
                return this.cnaePrincipalField;
            }
            set {
                this.cnaePrincipalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cnaeSecundaria", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] cnaeSecundaria {
            get {
                return this.cnaeSecundariaField;
            }
            set {
                this.cnaeSecundariaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tipoUnidade", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] tipoUnidade {
            get {
                return this.tipoUnidadeField;
            }
            set {
                this.tipoUnidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("formaAtuacao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] formaAtuacao {
            get {
                return this.formaAtuacaoField;
            }
            set {
                this.formaAtuacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cnpjFilial", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] cnpjFilial {
            get {
                return this.cnpjFilialField;
            }
            set {
                this.cnpjFilialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ufFilial", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] ufFilial {
            get {
                return this.ufFilialField;
            }
            set {
                this.ufFilialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("numeroRegistroFilial", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] numeroRegistroFilial {
            get {
                return this.numeroRegistroFilialField;
            }
            set {
                this.numeroRegistroFilialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpjMatriz {
            get {
                return this.cnpjMatrizField;
            }
            set {
                this.cnpjMatrizField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ufMatriz {
            get {
                return this.ufMatrizField;
            }
            set {
                this.ufMatrizField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroRegistroMatriz {
            get {
                return this.numeroRegistroMatrizField;
            }
            set {
                this.numeroRegistroMatrizField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dadosSocio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public dadosSocio[] dadosSocio {
            get {
                return this.dadosSocioField;
            }
            set {
                this.dadosSocioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class retornoWS11Redesim {
        
        private string codServicoField;
        
        private string versaoField;
        
        private string numeroProtocoloField;
        
        private int numeroOcorrenciaField;
        
        private bool numeroOcorrenciaFieldSpecified;
        
        private string codEventoField;
        
        private string reciboSolicitacaoField;
        
        private string identificacaoSolicitacaoField;
        
        private dadosCNPJ[] dadosCNPJField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codServico {
            get {
                return this.codServicoField;
            }
            set {
                this.codServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroProtocolo {
            get {
                return this.numeroProtocoloField;
            }
            set {
                this.numeroProtocoloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numeroOcorrencia {
            get {
                return this.numeroOcorrenciaField;
            }
            set {
                this.numeroOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroOcorrenciaSpecified {
            get {
                return this.numeroOcorrenciaFieldSpecified;
            }
            set {
                this.numeroOcorrenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codEvento {
            get {
                return this.codEventoField;
            }
            set {
                this.codEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reciboSolicitacao {
            get {
                return this.reciboSolicitacaoField;
            }
            set {
                this.reciboSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacaoSolicitacao {
            get {
                return this.identificacaoSolicitacaoField;
            }
            set {
                this.identificacaoSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dadosCNPJ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dadosCNPJ[] dadosCNPJ {
            get {
                return this.dadosCNPJField;
            }
            set {
                this.dadosCNPJField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class retornoWSRedesim {
        
        private string statusEnvioField;
        
        private string codigoRetornoField;
        
        private string descricaoRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string statusEnvio {
            get {
                return this.statusEnvioField;
            }
            set {
                this.statusEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoRetorno {
            get {
                return this.descricaoRetornoField;
            }
            set {
                this.descricaoRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class consultaCNPJResponse {
        
        private retornoWSRedesim retornoWSRedesimField;
        
        private retornoWS11Redesim retornoWS11RedesimField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public retornoWSRedesim retornoWSRedesim {
            get {
                return this.retornoWSRedesimField;
            }
            set {
                this.retornoWSRedesimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public retornoWS11Redesim retornoWS11Redesim {
            get {
                return this.retornoWS11RedesimField;
            }
            set {
                this.retornoWS11RedesimField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void consultaCNPJCompletedEventHandler(object sender, consultaCNPJCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaCNPJCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaCNPJCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public consultaCNPJResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((consultaCNPJResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591