//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsRFBReginV2.RJ_Servico_S99_V2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resultado", Namespace="http://schemas.datacontract.org/2004/07/jucerja.rj.servicos")]
    [System.SerializableAttribute()]
    public partial class Resultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Codigok__BackingFieldField;
        
        private string Mensagemk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Codigo>k__BackingField", IsRequired=true)]
        public string Codigok__BackingField {
            get {
                return this.Codigok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Codigok__BackingFieldField, value) != true)) {
                    this.Codigok__BackingFieldField = value;
                    this.RaisePropertyChanged("Codigok__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Mensagem>k__BackingField", IsRequired=true)]
        public string Mensagemk__BackingField {
            get {
                return this.Mensagemk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Mensagemk__BackingFieldField, value) != true)) {
                    this.Mensagemk__BackingFieldField = value;
                    this.RaisePropertyChanged("Mensagemk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RJ_Servico_S99_V2.IServicoIntegracaoS99")]
    public interface IServicoIntegracaoS99 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoIntegracaoS99/EnviarS99", ReplyAction="http://tempuri.org/IServicoIntegracaoS99/EnviarS99Response")]
        WsRFBReginV2.RJ_Servico_S99_V2.Resultado EnviarS99(string xmlS99);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoIntegracaoS99/EnviarS99", ReplyAction="http://tempuri.org/IServicoIntegracaoS99/EnviarS99Response")]
        System.Threading.Tasks.Task<WsRFBReginV2.RJ_Servico_S99_V2.Resultado> EnviarS99Async(string xmlS99);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoIntegracaoS99Channel : WsRFBReginV2.RJ_Servico_S99_V2.IServicoIntegracaoS99, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoIntegracaoS99Client : System.ServiceModel.ClientBase<WsRFBReginV2.RJ_Servico_S99_V2.IServicoIntegracaoS99>, WsRFBReginV2.RJ_Servico_S99_V2.IServicoIntegracaoS99 {
        
        public ServicoIntegracaoS99Client() {
        }
        
        public ServicoIntegracaoS99Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoIntegracaoS99Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoIntegracaoS99Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoIntegracaoS99Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WsRFBReginV2.RJ_Servico_S99_V2.Resultado EnviarS99(string xmlS99) {
            return base.Channel.EnviarS99(xmlS99);
        }
        
        public System.Threading.Tasks.Task<WsRFBReginV2.RJ_Servico_S99_V2.Resultado> EnviarS99Async(string xmlS99) {
            return base.Channel.EnviarS99Async(xmlS99);
        }
    }
}
