//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WsRFBReginV2.WsServices53RFB {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ws53SoapBinding", Namespace="http://redesim.serpro.gov.br/")]
    public partial class ws53 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback enviarOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ws53() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::WsRFBReginV2.Properties.Settings.Default.WsRFBReginV2_WsServices53RFB_ws53;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event enviarCompletedEventHandler enviarCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("serviceResponse", Namespace="http://redesim.serpro.gov.br/")]
        public serviceResponse enviar([System.Xml.Serialization.XmlElementAttribute(Namespace="http://redesim.serpro.gov.br/")] serviceRequest serviceRequest) {
            object[] results = this.Invoke("enviar", new object[] {
                        serviceRequest});
            return ((serviceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void enviarAsync(serviceRequest serviceRequest) {
            this.enviarAsync(serviceRequest, null);
        }
        
        /// <remarks/>
        public void enviarAsync(serviceRequest serviceRequest, object userState) {
            if ((this.enviarOperationCompleted == null)) {
                this.enviarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarOperationCompleted);
            }
            this.InvokeAsync("enviar", new object[] {
                        serviceRequest}, this.enviarOperationCompleted, userState);
        }
        
        private void OnenviarOperationCompleted(object arg) {
            if ((this.enviarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarCompleted(this, new enviarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class serviceRequest {
        
        private string codServicoField;
        
        private string versaoField;
        
        private string numeroProtocoloField;
        
        private int numeroOcorrenciaField;
        
        private string usoRFBField;
        
        private string cpfPreenchedorField;
        
        private viabilidade viabilidadeField;
        
        private dadosComplementares dadosComplementaresField;
        
        private socio[] sociosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codServico {
            get {
                return this.codServicoField;
            }
            set {
                this.codServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroProtocolo {
            get {
                return this.numeroProtocoloField;
            }
            set {
                this.numeroProtocoloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numeroOcorrencia {
            get {
                return this.numeroOcorrenciaField;
            }
            set {
                this.numeroOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usoRFB {
            get {
                return this.usoRFBField;
            }
            set {
                this.usoRFBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfPreenchedor {
            get {
                return this.cpfPreenchedorField;
            }
            set {
                this.cpfPreenchedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public viabilidade viabilidade {
            get {
                return this.viabilidadeField;
            }
            set {
                this.viabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dadosComplementares dadosComplementares {
            get {
                return this.dadosComplementaresField;
            }
            set {
                this.dadosComplementaresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("socios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public socio[] socios {
            get {
                return this.sociosField;
            }
            set {
                this.sociosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class viabilidade {
        
        private string[] codEventosViabilidadeField;
        
        private string codStatusViabilidadeField;
        
        private string dataValidadeViabilidadeField;
        
        private string resultadoViabilidadeNomeField;
        
        private string resultadoViabilidadeEnderecoField;
        
        private string dataInicioAnaliseViabilidadeField;
        
        private string dataFimAnaliseViabilidadeNomeField;
        
        private string dataFimAnaliseViabilidadeEnderecoField;
        
        private string indicadorCnpjNomeEmpresarialField;
        
        private string nomeEmpresarialField;
        
        private string codNaturezaJuridicaField;
        
        private string codTipoOrgaoRegistroField;
        
        private string cnpjField;
        
        private endereco enderecoField;
        
        private ativEcon atividadeEconomicaField;
        
        private string[] nomeSocioPfField;
        
        private string[] cpfSocioPfField;
        
        private string indicadorContabilistaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codEventosViabilidade", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] codEventosViabilidade {
            get {
                return this.codEventosViabilidadeField;
            }
            set {
                this.codEventosViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codStatusViabilidade {
            get {
                return this.codStatusViabilidadeField;
            }
            set {
                this.codStatusViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataValidadeViabilidade {
            get {
                return this.dataValidadeViabilidadeField;
            }
            set {
                this.dataValidadeViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultadoViabilidadeNome {
            get {
                return this.resultadoViabilidadeNomeField;
            }
            set {
                this.resultadoViabilidadeNomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultadoViabilidadeEndereco {
            get {
                return this.resultadoViabilidadeEnderecoField;
            }
            set {
                this.resultadoViabilidadeEnderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataInicioAnaliseViabilidade {
            get {
                return this.dataInicioAnaliseViabilidadeField;
            }
            set {
                this.dataInicioAnaliseViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataFimAnaliseViabilidadeNome {
            get {
                return this.dataFimAnaliseViabilidadeNomeField;
            }
            set {
                this.dataFimAnaliseViabilidadeNomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataFimAnaliseViabilidadeEndereco {
            get {
                return this.dataFimAnaliseViabilidadeEnderecoField;
            }
            set {
                this.dataFimAnaliseViabilidadeEnderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indicadorCnpjNomeEmpresarial {
            get {
                return this.indicadorCnpjNomeEmpresarialField;
            }
            set {
                this.indicadorCnpjNomeEmpresarialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeEmpresarial {
            get {
                return this.nomeEmpresarialField;
            }
            set {
                this.nomeEmpresarialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codNaturezaJuridica {
            get {
                return this.codNaturezaJuridicaField;
            }
            set {
                this.codNaturezaJuridicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoOrgaoRegistro {
            get {
                return this.codTipoOrgaoRegistroField;
            }
            set {
                this.codTipoOrgaoRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ativEcon atividadeEconomica {
            get {
                return this.atividadeEconomicaField;
            }
            set {
                this.atividadeEconomicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nomeSocioPf", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] nomeSocioPf {
            get {
                return this.nomeSocioPfField;
            }
            set {
                this.nomeSocioPfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cpfSocioPf", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] cpfSocioPf {
            get {
                return this.cpfSocioPfField;
            }
            set {
                this.cpfSocioPfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indicadorContabilista {
            get {
                return this.indicadorContabilistaField;
            }
            set {
                this.indicadorContabilistaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class endereco {
        
        private string indOrigemEnderecoField;
        
        private string cepField;
        
        private string ufField;
        
        private string codMunicipioField;
        
        private string codTipoLogradouroField;
        
        private string logradouroField;
        
        private string numLogradouroField;
        
        private complementoLogradouro[] complementoLogradouroField;
        
        private string bairroField;
        
        private string distritoField;
        
        private string referenciaField;
        
        private string cidadeExteriorField;
        
        private string codPaisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indOrigemEndereco {
            get {
                return this.indOrigemEnderecoField;
            }
            set {
                this.indOrigemEnderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codMunicipio {
            get {
                return this.codMunicipioField;
            }
            set {
                this.codMunicipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoLogradouro {
            get {
                return this.codTipoLogradouroField;
            }
            set {
                this.codTipoLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numLogradouro {
            get {
                return this.numLogradouroField;
            }
            set {
                this.numLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("complementoLogradouro", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public complementoLogradouro[] complementoLogradouro {
            get {
                return this.complementoLogradouroField;
            }
            set {
                this.complementoLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cidadeExterior {
            get {
                return this.cidadeExteriorField;
            }
            set {
                this.cidadeExteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPais {
            get {
                return this.codPaisField;
            }
            set {
                this.codPaisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class complementoLogradouro {
        
        private string tipoComplementoLogradouroField;
        
        private string descricaoComplementoLogradouroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoComplementoLogradouro {
            get {
                return this.tipoComplementoLogradouroField;
            }
            set {
                this.tipoComplementoLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoComplementoLogradouro {
            get {
                return this.descricaoComplementoLogradouroField;
            }
            set {
                this.descricaoComplementoLogradouroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class mensagemRetorno {
        
        private string codigoRetornoField;
        
        private string descricaoRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoRetorno {
            get {
                return this.descricaoRetornoField;
            }
            set {
                this.descricaoRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class retornoWSRedesim {
        
        private string statusEnvioField;
        
        private string codigoRetornoField;
        
        private string descricaoRetornoField;
        
        private string reciboSolicitacaoField;
        
        private string identificacaoSolicitacaoField;
        
        private mensagemRetorno[] mensagemRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string statusEnvio {
            get {
                return this.statusEnvioField;
            }
            set {
                this.statusEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoRetorno {
            get {
                return this.descricaoRetornoField;
            }
            set {
                this.descricaoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reciboSolicitacao {
            get {
                return this.reciboSolicitacaoField;
            }
            set {
                this.reciboSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacaoSolicitacao {
            get {
                return this.identificacaoSolicitacaoField;
            }
            set {
                this.identificacaoSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensagemRetorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mensagemRetorno[] mensagemRetorno {
            get {
                return this.mensagemRetornoField;
            }
            set {
                this.mensagemRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class serviceResponse {
        
        private retornoWSRedesim retornoWSRedesimField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public retornoWSRedesim retornoWSRedesim {
            get {
                return this.retornoWSRedesimField;
            }
            set {
                this.retornoWSRedesimField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class integralizacaoCapitalSocio {
        
        private string formaIntegralizacaoField;
        
        private string valorIntegralizacaoField;
        
        private string dataIntegralizacaoField;
        
        private string dataIntegralizarField;
        
        private string numRegistroField;
        
        private string numMatriculaField;
        
        private string identificacaoTitularImovelField;
        
        private string identificacaoCartorioField;
        
        private string cnpjCotasIntegralizarField;
        
        private string qtdeCotasCnpjIntegralizarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string formaIntegralizacao {
            get {
                return this.formaIntegralizacaoField;
            }
            set {
                this.formaIntegralizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valorIntegralizacao {
            get {
                return this.valorIntegralizacaoField;
            }
            set {
                this.valorIntegralizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataIntegralizacao {
            get {
                return this.dataIntegralizacaoField;
            }
            set {
                this.dataIntegralizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataIntegralizar {
            get {
                return this.dataIntegralizarField;
            }
            set {
                this.dataIntegralizarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numRegistro {
            get {
                return this.numRegistroField;
            }
            set {
                this.numRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numMatricula {
            get {
                return this.numMatriculaField;
            }
            set {
                this.numMatriculaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacaoTitularImovel {
            get {
                return this.identificacaoTitularImovelField;
            }
            set {
                this.identificacaoTitularImovelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacaoCartorio {
            get {
                return this.identificacaoCartorioField;
            }
            set {
                this.identificacaoCartorioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpjCotasIntegralizar {
            get {
                return this.cnpjCotasIntegralizarField;
            }
            set {
                this.cnpjCotasIntegralizarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string qtdeCotasCnpjIntegralizar {
            get {
                return this.qtdeCotasCnpjIntegralizarField;
            }
            set {
                this.qtdeCotasCnpjIntegralizarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class socio {
        
        private string indicadorRepresentantePJField;
        
        private string codEventoField;
        
        private string indCnpjCpfSocioField;
        
        private string cnpjCpfSocioField;
        
        private string socio1Field;
        
        private string codQualificacaoSocioField;
        
        private string codPaisField;
        
        private string valorParticipacaoCapitalSocialField;
        
        private string valorIntegralizadoField;
        
        private string valorIntegralizarField;
        
        private string qtdeQuotasField;
        
        private integralizacaoCapitalSocio[] integralizacaoCapitalSocioField;
        
        private string estadoCivilField;
        
        private string comunhaoBensField;
        
        private string indicadorEmancipacaoField;
        
        private string tipoEmancipacaoField;
        
        private endereco endSocioField;
        
        private contato contatoSocioField;
        
        private string representanteLegalSocioField;
        
        private string codQualificacaoRepresentanteLegalSocioField;
        
        private string cpfRepresentanteLegalSocioField;
        
        private endereco endRepLegalField;
        
        private contato contatoRepLegalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indicadorRepresentantePJ {
            get {
                return this.indicadorRepresentantePJField;
            }
            set {
                this.indicadorRepresentantePJField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codEvento {
            get {
                return this.codEventoField;
            }
            set {
                this.codEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indCnpjCpfSocio {
            get {
                return this.indCnpjCpfSocioField;
            }
            set {
                this.indCnpjCpfSocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpjCpfSocio {
            get {
                return this.cnpjCpfSocioField;
            }
            set {
                this.cnpjCpfSocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("socio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string socio1 {
            get {
                return this.socio1Field;
            }
            set {
                this.socio1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codQualificacaoSocio {
            get {
                return this.codQualificacaoSocioField;
            }
            set {
                this.codQualificacaoSocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPais {
            get {
                return this.codPaisField;
            }
            set {
                this.codPaisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valorParticipacaoCapitalSocial {
            get {
                return this.valorParticipacaoCapitalSocialField;
            }
            set {
                this.valorParticipacaoCapitalSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valorIntegralizado {
            get {
                return this.valorIntegralizadoField;
            }
            set {
                this.valorIntegralizadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valorIntegralizar {
            get {
                return this.valorIntegralizarField;
            }
            set {
                this.valorIntegralizarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string qtdeQuotas {
            get {
                return this.qtdeQuotasField;
            }
            set {
                this.qtdeQuotasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("integralizacaoCapitalSocio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public integralizacaoCapitalSocio[] integralizacaoCapitalSocio {
            get {
                return this.integralizacaoCapitalSocioField;
            }
            set {
                this.integralizacaoCapitalSocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string comunhaoBens {
            get {
                return this.comunhaoBensField;
            }
            set {
                this.comunhaoBensField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indicadorEmancipacao {
            get {
                return this.indicadorEmancipacaoField;
            }
            set {
                this.indicadorEmancipacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoEmancipacao {
            get {
                return this.tipoEmancipacaoField;
            }
            set {
                this.tipoEmancipacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco endSocio {
            get {
                return this.endSocioField;
            }
            set {
                this.endSocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contato contatoSocio {
            get {
                return this.contatoSocioField;
            }
            set {
                this.contatoSocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string representanteLegalSocio {
            get {
                return this.representanteLegalSocioField;
            }
            set {
                this.representanteLegalSocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codQualificacaoRepresentanteLegalSocio {
            get {
                return this.codQualificacaoRepresentanteLegalSocioField;
            }
            set {
                this.codQualificacaoRepresentanteLegalSocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfRepresentanteLegalSocio {
            get {
                return this.cpfRepresentanteLegalSocioField;
            }
            set {
                this.cpfRepresentanteLegalSocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco endRepLegal {
            get {
                return this.endRepLegalField;
            }
            set {
                this.endRepLegalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contato contatoRepLegal {
            get {
                return this.contatoRepLegalField;
            }
            set {
                this.contatoRepLegalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class contato {
        
        private string dddTelefone1Field;
        
        private string telefone1Field;
        
        private string dddTelefone2Field;
        
        private string telefone2Field;
        
        private string correioEletronicoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dddTelefone1 {
            get {
                return this.dddTelefone1Field;
            }
            set {
                this.dddTelefone1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefone1 {
            get {
                return this.telefone1Field;
            }
            set {
                this.telefone1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dddTelefone2 {
            get {
                return this.dddTelefone2Field;
            }
            set {
                this.dddTelefone2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefone2 {
            get {
                return this.telefone2Field;
            }
            set {
                this.telefone2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correioEletronico {
            get {
                return this.correioEletronicoField;
            }
            set {
                this.correioEletronicoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class quotasEmpresa {
        
        private string qtdeQuotasField;
        
        private string valorQuotaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string qtdeQuotas {
            get {
                return this.qtdeQuotasField;
            }
            set {
                this.qtdeQuotasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valorQuota {
            get {
                return this.valorQuotaField;
            }
            set {
                this.valorQuotaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class dadosComplementares {
        
        private string empresaComEstabelecimentoField;
        
        private string nomeFantasiaField;
        
        private string capitalSocialField;
        
        private string capitalIntegralizadoField;
        
        private string capitalIntegralizarField;
        
        private quotasEmpresa quotasEmpresaField;
        
        private contato contatoEmpresaField;
        
        private endereco enderecoCorrespondenciaField;
        
        private string codPorteEmpresaField;
        
        private string indicadorPrazoDuracaoAtividadeField;
        
        private string dataInicioAtividadesField;
        
        private string dataTerminoAtividadesField;
        
        private string dataAssinaturaContratoField;
        
        private string cpfAdvogadoField;
        
        private string nomeAdvogadoField;
        
        private string registroOABField;
        
        private string ufOABField;
        
        private string codClassificCRCcontadorPFField;
        
        private string ufContadorPFField;
        
        private string numSeqContadorPFField;
        
        private string codTipoCRCcontadorPFField;
        
        private string cpfContadorPFField;
        
        private string nomeContadorPFField;
        
        private string codClassificEmpresaContabilField;
        
        private string ufCRCempresaContabilField;
        
        private string seqCRCempresaContabilField;
        
        private string codTipoCRCempresaContabilField;
        
        private string cnpjEmpresaContabilField;
        
        private string nomeEmpresaContabilField;
        
        private endereco endContadorPfField;
        
        private contato contatoContadorPfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string empresaComEstabelecimento {
            get {
                return this.empresaComEstabelecimentoField;
            }
            set {
                this.empresaComEstabelecimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeFantasia {
            get {
                return this.nomeFantasiaField;
            }
            set {
                this.nomeFantasiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string capitalSocial {
            get {
                return this.capitalSocialField;
            }
            set {
                this.capitalSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string capitalIntegralizado {
            get {
                return this.capitalIntegralizadoField;
            }
            set {
                this.capitalIntegralizadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string capitalIntegralizar {
            get {
                return this.capitalIntegralizarField;
            }
            set {
                this.capitalIntegralizarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public quotasEmpresa quotasEmpresa {
            get {
                return this.quotasEmpresaField;
            }
            set {
                this.quotasEmpresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contato contatoEmpresa {
            get {
                return this.contatoEmpresaField;
            }
            set {
                this.contatoEmpresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco enderecoCorrespondencia {
            get {
                return this.enderecoCorrespondenciaField;
            }
            set {
                this.enderecoCorrespondenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPorteEmpresa {
            get {
                return this.codPorteEmpresaField;
            }
            set {
                this.codPorteEmpresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indicadorPrazoDuracaoAtividade {
            get {
                return this.indicadorPrazoDuracaoAtividadeField;
            }
            set {
                this.indicadorPrazoDuracaoAtividadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataInicioAtividades {
            get {
                return this.dataInicioAtividadesField;
            }
            set {
                this.dataInicioAtividadesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataTerminoAtividades {
            get {
                return this.dataTerminoAtividadesField;
            }
            set {
                this.dataTerminoAtividadesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataAssinaturaContrato {
            get {
                return this.dataAssinaturaContratoField;
            }
            set {
                this.dataAssinaturaContratoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfAdvogado {
            get {
                return this.cpfAdvogadoField;
            }
            set {
                this.cpfAdvogadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeAdvogado {
            get {
                return this.nomeAdvogadoField;
            }
            set {
                this.nomeAdvogadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string registroOAB {
            get {
                return this.registroOABField;
            }
            set {
                this.registroOABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ufOAB {
            get {
                return this.ufOABField;
            }
            set {
                this.ufOABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codClassificCRCcontadorPF {
            get {
                return this.codClassificCRCcontadorPFField;
            }
            set {
                this.codClassificCRCcontadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ufContadorPF {
            get {
                return this.ufContadorPFField;
            }
            set {
                this.ufContadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numSeqContadorPF {
            get {
                return this.numSeqContadorPFField;
            }
            set {
                this.numSeqContadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoCRCcontadorPF {
            get {
                return this.codTipoCRCcontadorPFField;
            }
            set {
                this.codTipoCRCcontadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfContadorPF {
            get {
                return this.cpfContadorPFField;
            }
            set {
                this.cpfContadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeContadorPF {
            get {
                return this.nomeContadorPFField;
            }
            set {
                this.nomeContadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codClassificEmpresaContabil {
            get {
                return this.codClassificEmpresaContabilField;
            }
            set {
                this.codClassificEmpresaContabilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ufCRCempresaContabil {
            get {
                return this.ufCRCempresaContabilField;
            }
            set {
                this.ufCRCempresaContabilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string seqCRCempresaContabil {
            get {
                return this.seqCRCempresaContabilField;
            }
            set {
                this.seqCRCempresaContabilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoCRCempresaContabil {
            get {
                return this.codTipoCRCempresaContabilField;
            }
            set {
                this.codTipoCRCempresaContabilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpjEmpresaContabil {
            get {
                return this.cnpjEmpresaContabilField;
            }
            set {
                this.cnpjEmpresaContabilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeEmpresaContabil {
            get {
                return this.nomeEmpresaContabilField;
            }
            set {
                this.nomeEmpresaContabilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco endContadorPf {
            get {
                return this.endContadorPfField;
            }
            set {
                this.endContadorPfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contato contatoContadorPf {
            get {
                return this.contatoContadorPfField;
            }
            set {
                this.contatoContadorPfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class ativEcon {
        
        private string codCnaeFiscalField;
        
        private string[] codCnaeSecundariaField;
        
        private string[] codFormaDeAtuacaoField;
        
        private string[] codTipoUnidadeField;
        
        private string objetoSocialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codCnaeFiscal {
            get {
                return this.codCnaeFiscalField;
            }
            set {
                this.codCnaeFiscalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codCnaeSecundaria", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] codCnaeSecundaria {
            get {
                return this.codCnaeSecundariaField;
            }
            set {
                this.codCnaeSecundariaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codFormaDeAtuacao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] codFormaDeAtuacao {
            get {
                return this.codFormaDeAtuacaoField;
            }
            set {
                this.codFormaDeAtuacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codTipoUnidade", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] codTipoUnidade {
            get {
                return this.codTipoUnidadeField;
            }
            set {
                this.codTipoUnidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string objetoSocial {
            get {
                return this.objetoSocialField;
            }
            set {
                this.objetoSocialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void enviarCompletedEventHandler(object sender, enviarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public serviceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((serviceResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591