//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WsRFBReginV2.WsServices09RFB {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS09HttpSoapBinding", Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class WS09Serviceserviceagent : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultaCPFOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS09Serviceserviceagent() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::WsRFBReginV2.Properties.Settings.Default.WsRFBReginV2_WsServices09RFB_WS09Service_serviceagent;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultaCPFCompletedEventHandler consultaCPFCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("/ws09-service0.serviceagent/WS09Endpoint0/consultaCPF", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultaCPFResponse", Namespace="http://servicos.integrador.serpro.gov.br/")]
        public consultaCPFResponse consultaCPF([System.Xml.Serialization.XmlElementAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")] consultaCPFRequest consultaCPFRequest) {
            object[] results = this.Invoke("consultaCPF", new object[] {
                        consultaCPFRequest});
            return ((consultaCPFResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultaCPFAsync(consultaCPFRequest consultaCPFRequest) {
            this.consultaCPFAsync(consultaCPFRequest, null);
        }
        
        /// <remarks/>
        public void consultaCPFAsync(consultaCPFRequest consultaCPFRequest, object userState) {
            if ((this.consultaCPFOperationCompleted == null)) {
                this.consultaCPFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaCPFOperationCompleted);
            }
            this.InvokeAsync("consultaCPF", new object[] {
                        consultaCPFRequest}, this.consultaCPFOperationCompleted, userState);
        }
        
        private void OnconsultaCPFOperationCompleted(object arg) {
            if ((this.consultaCPFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaCPFCompleted(this, new consultaCPFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class consultaCPFRequest {
        
        private string codServicoField;
        
        private string versaoField;
        
        private string usoRFBField;
        
        private string numeroProtocoloField;
        
        private int numeroOcorrenciaField;
        
        private bool numeroOcorrenciaFieldSpecified;
        
        private string codEventoField;
        
        private string[] cpfField;
        
        private string reciboSolicitacaoField;
        
        private string identificacaoSolicitacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codServico {
            get {
                return this.codServicoField;
            }
            set {
                this.codServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usoRFB {
            get {
                return this.usoRFBField;
            }
            set {
                this.usoRFBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroProtocolo {
            get {
                return this.numeroProtocoloField;
            }
            set {
                this.numeroProtocoloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numeroOcorrencia {
            get {
                return this.numeroOcorrenciaField;
            }
            set {
                this.numeroOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroOcorrenciaSpecified {
            get {
                return this.numeroOcorrenciaFieldSpecified;
            }
            set {
                this.numeroOcorrenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codEvento {
            get {
                return this.codEventoField;
            }
            set {
                this.codEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cpf", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reciboSolicitacao {
            get {
                return this.reciboSolicitacaoField;
            }
            set {
                this.reciboSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacaoSolicitacao {
            get {
                return this.identificacaoSolicitacaoField;
            }
            set {
                this.identificacaoSolicitacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class endereco09 {
        
        private string indOrigemEnderecoField;
        
        private string cepField;
        
        private string ufField;
        
        private string codMunicipioField;
        
        private string codTipoLogradouroField;
        
        private string logradouroField;
        
        private string numLogradouroField;
        
        private string complementoLogradouroField;
        
        private string bairroField;
        
        private string distritoField;
        
        private string referenciaField;
        
        private string cidadeExteriorField;
        
        private string codPaisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indOrigemEndereco {
            get {
                return this.indOrigemEnderecoField;
            }
            set {
                this.indOrigemEnderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codMunicipio {
            get {
                return this.codMunicipioField;
            }
            set {
                this.codMunicipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoLogradouro {
            get {
                return this.codTipoLogradouroField;
            }
            set {
                this.codTipoLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numLogradouro {
            get {
                return this.numLogradouroField;
            }
            set {
                this.numLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string complementoLogradouro {
            get {
                return this.complementoLogradouroField;
            }
            set {
                this.complementoLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cidadeExterior {
            get {
                return this.cidadeExteriorField;
            }
            set {
                this.cidadeExteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPais {
            get {
                return this.codPaisField;
            }
            set {
                this.codPaisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class dadosCPF {
        
        private string numCPFField;
        
        private string nomeField;
        
        private string dataNascimentoField;
        
        private string sexoField;
        
        private string residenteExteriorField;
        
        private string situacaoCadastralField;
        
        private endereco09 enderecoField;
        
        private string nacionalidadeField;
        
        private string nomeMaeField;
        
        private string naturalidadeField;
        
        private string anoObitoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numCPF {
            get {
                return this.numCPFField;
            }
            set {
                this.numCPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataNascimento {
            get {
                return this.dataNascimentoField;
            }
            set {
                this.dataNascimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string residenteExterior {
            get {
                return this.residenteExteriorField;
            }
            set {
                this.residenteExteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string situacaoCadastral {
            get {
                return this.situacaoCadastralField;
            }
            set {
                this.situacaoCadastralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco09 endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nacionalidade {
            get {
                return this.nacionalidadeField;
            }
            set {
                this.nacionalidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeMae {
            get {
                return this.nomeMaeField;
            }
            set {
                this.nomeMaeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string naturalidade {
            get {
                return this.naturalidadeField;
            }
            set {
                this.naturalidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string anoObito {
            get {
                return this.anoObitoField;
            }
            set {
                this.anoObitoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class retornoWS09Redesim {
        
        private string codServicoField;
        
        private string versaoField;
        
        private string numeroProtocoloField;
        
        private int numeroOcorrenciaField;
        
        private bool numeroOcorrenciaFieldSpecified;
        
        private string codEventoField;
        
        private string reciboSolicitacaoField;
        
        private string identificacaoSolicitacaoField;
        
        private dadosCPF[] dadosCPFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codServico {
            get {
                return this.codServicoField;
            }
            set {
                this.codServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroProtocolo {
            get {
                return this.numeroProtocoloField;
            }
            set {
                this.numeroProtocoloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numeroOcorrencia {
            get {
                return this.numeroOcorrenciaField;
            }
            set {
                this.numeroOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroOcorrenciaSpecified {
            get {
                return this.numeroOcorrenciaFieldSpecified;
            }
            set {
                this.numeroOcorrenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codEvento {
            get {
                return this.codEventoField;
            }
            set {
                this.codEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reciboSolicitacao {
            get {
                return this.reciboSolicitacaoField;
            }
            set {
                this.reciboSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacaoSolicitacao {
            get {
                return this.identificacaoSolicitacaoField;
            }
            set {
                this.identificacaoSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dadosCPF", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dadosCPF[] dadosCPF {
            get {
                return this.dadosCPFField;
            }
            set {
                this.dadosCPFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class retornoWSRedesim {
        
        private string statusEnvioField;
        
        private string codigoRetornoField;
        
        private string descricaoRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string statusEnvio {
            get {
                return this.statusEnvioField;
            }
            set {
                this.statusEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoRetorno {
            get {
                return this.descricaoRetornoField;
            }
            set {
                this.descricaoRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class consultaCPFResponse {
        
        private retornoWSRedesim retornoWSRedesimField;
        
        private retornoWS09Redesim retornoWS09RedesimField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public retornoWSRedesim retornoWSRedesim {
            get {
                return this.retornoWSRedesimField;
            }
            set {
                this.retornoWSRedesimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public retornoWS09Redesim retornoWS09Redesim {
            get {
                return this.retornoWS09RedesimField;
            }
            set {
                this.retornoWS09RedesimField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void consultaCPFCompletedEventHandler(object sender, consultaCPFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaCPFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaCPFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public consultaCPFResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((consultaCPFResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591