//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WsRFBReginV2.WsServices22RFB {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS22HttpSoapBinding", Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class WS22Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback comunicarCancelamentoSolicitacaoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS22Service() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::WsRFBReginV2.Properties.Settings.Default.WsRFBReginV2_WsServices22RFB_WS22Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event comunicarCancelamentoSolicitacaoCompletedEventHandler comunicarCancelamentoSolicitacaoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("/WS22Service.serviceagent/WS22HttpSoap/comunicarCancelamentoSolicitacao", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("comunicarCancelamentoSolicitacaoResponse", Namespace="http://servicos.integrador.serpro.gov.br/")]
        public comunicarCancelamentoSolicitacaoResponse comunicarCancelamentoSolicitacao([System.Xml.Serialization.XmlElementAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")] comunicarCancelamentoSolicitacaoRequest comunicarCancelamentoSolicitacaoRequest) {
            object[] results = this.Invoke("comunicarCancelamentoSolicitacao", new object[] {
                        comunicarCancelamentoSolicitacaoRequest});
            return ((comunicarCancelamentoSolicitacaoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void comunicarCancelamentoSolicitacaoAsync(comunicarCancelamentoSolicitacaoRequest comunicarCancelamentoSolicitacaoRequest) {
            this.comunicarCancelamentoSolicitacaoAsync(comunicarCancelamentoSolicitacaoRequest, null);
        }
        
        /// <remarks/>
        public void comunicarCancelamentoSolicitacaoAsync(comunicarCancelamentoSolicitacaoRequest comunicarCancelamentoSolicitacaoRequest, object userState) {
            if ((this.comunicarCancelamentoSolicitacaoOperationCompleted == null)) {
                this.comunicarCancelamentoSolicitacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncomunicarCancelamentoSolicitacaoOperationCompleted);
            }
            this.InvokeAsync("comunicarCancelamentoSolicitacao", new object[] {
                        comunicarCancelamentoSolicitacaoRequest}, this.comunicarCancelamentoSolicitacaoOperationCompleted, userState);
        }
        
        private void OncomunicarCancelamentoSolicitacaoOperationCompleted(object arg) {
            if ((this.comunicarCancelamentoSolicitacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.comunicarCancelamentoSolicitacaoCompleted(this, new comunicarCancelamentoSolicitacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class comunicarCancelamentoSolicitacaoRequest {
        
        private string codServicoField;
        
        private string usoRFBField;
        
        private string numeroProtocoloField;
        
        private string numeroOcorrenciaField;
        
        private string versaoField;
        
        private string reciboSolicitacaoField;
        
        private string identificacaoSolicitacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codServico {
            get {
                return this.codServicoField;
            }
            set {
                this.codServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usoRFB {
            get {
                return this.usoRFBField;
            }
            set {
                this.usoRFBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroProtocolo {
            get {
                return this.numeroProtocoloField;
            }
            set {
                this.numeroProtocoloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroOcorrencia {
            get {
                return this.numeroOcorrenciaField;
            }
            set {
                this.numeroOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reciboSolicitacao {
            get {
                return this.reciboSolicitacaoField;
            }
            set {
                this.reciboSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacaoSolicitacao {
            get {
                return this.identificacaoSolicitacaoField;
            }
            set {
                this.identificacaoSolicitacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class retornoWS22Redesim {
        
        private string codServicoField;
        
        private string numeroProtocoloField;
        
        private string numeroOcorrenciaField;
        
        private string informacaoCancelamentoSolicitacaoField;
        
        private string versaoField;
        
        private string reciboSolicitacaoField;
        
        private string identificacaoSolicitacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codServico {
            get {
                return this.codServicoField;
            }
            set {
                this.codServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroProtocolo {
            get {
                return this.numeroProtocoloField;
            }
            set {
                this.numeroProtocoloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroOcorrencia {
            get {
                return this.numeroOcorrenciaField;
            }
            set {
                this.numeroOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string informacaoCancelamentoSolicitacao {
            get {
                return this.informacaoCancelamentoSolicitacaoField;
            }
            set {
                this.informacaoCancelamentoSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reciboSolicitacao {
            get {
                return this.reciboSolicitacaoField;
            }
            set {
                this.reciboSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacaoSolicitacao {
            get {
                return this.identificacaoSolicitacaoField;
            }
            set {
                this.identificacaoSolicitacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class mensagemRetorno {
        
        private string codigoRetornoField;
        
        private string descricaoRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoRetorno {
            get {
                return this.descricaoRetornoField;
            }
            set {
                this.descricaoRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class retornoWSRedesim {
        
        private string statusEnvioField;
        
        private string codigoRetornoField;
        
        private string descricaoRetornoField;
        
        private mensagemRetorno[] mensagemRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string statusEnvio {
            get {
                return this.statusEnvioField;
            }
            set {
                this.statusEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoRetorno {
            get {
                return this.descricaoRetornoField;
            }
            set {
                this.descricaoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensagemRetorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mensagemRetorno[] mensagemRetorno {
            get {
                return this.mensagemRetornoField;
            }
            set {
                this.mensagemRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class comunicarCancelamentoSolicitacaoResponse {
        
        private retornoWSRedesim retornoWSRedesimField;
        
        private retornoWS22Redesim retornoWS22RedesimField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public retornoWSRedesim retornoWSRedesim {
            get {
                return this.retornoWSRedesimField;
            }
            set {
                this.retornoWSRedesimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public retornoWS22Redesim retornoWS22Redesim {
            get {
                return this.retornoWS22RedesimField;
            }
            set {
                this.retornoWS22RedesimField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void comunicarCancelamentoSolicitacaoCompletedEventHandler(object sender, comunicarCancelamentoSolicitacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class comunicarCancelamentoSolicitacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal comunicarCancelamentoSolicitacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public comunicarCancelamentoSolicitacaoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((comunicarCancelamentoSolicitacaoResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591