//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WsRFBReginV2.WsServices01RFB {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS01HttpSoapBinding", Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class WS01Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback processarViabilidadeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS01Service() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::WsRFBReginV2.Properties.Settings.Default.WsRFBReginV2_WsServices01RFB_WS01Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event processarViabilidadeCompletedEventHandler processarViabilidadeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("/WS01Service.serviceagent/WS01HttpSoap/processarViabilidade", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("processarViabilidadeResponse", Namespace="http://servicos.integrador.serpro.gov.br/")]
        public processarViabilidadeResponse processarViabilidade([System.Xml.Serialization.XmlElementAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")] processarViabilidadeRequest processarViabilidadeRequest) {
            object[] results = this.Invoke("processarViabilidade", new object[] {
                        processarViabilidadeRequest});
            return ((processarViabilidadeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void processarViabilidadeAsync(processarViabilidadeRequest processarViabilidadeRequest) {
            this.processarViabilidadeAsync(processarViabilidadeRequest, null);
        }
        
        /// <remarks/>
        public void processarViabilidadeAsync(processarViabilidadeRequest processarViabilidadeRequest, object userState) {
            if ((this.processarViabilidadeOperationCompleted == null)) {
                this.processarViabilidadeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessarViabilidadeOperationCompleted);
            }
            this.InvokeAsync("processarViabilidade", new object[] {
                        processarViabilidadeRequest}, this.processarViabilidadeOperationCompleted, userState);
        }
        
        private void OnprocessarViabilidadeOperationCompleted(object arg) {
            if ((this.processarViabilidadeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processarViabilidadeCompleted(this, new processarViabilidadeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class processarViabilidadeRequest {
        
        private string codServicoField;
        
        private string usoRFBField;
        
        private string[] codEventosViabilidadeField;
        
        private string codStatusViabilidadeField;
        
        private string protocoloViabilidadeField;
        
        private string protocoloRLEField;
        
        private string dataValidadeViabilidadeField;
        
        private string resultadoViabilidadeNomeField;
        
        private string resultadoViabilidadeEnderecoField;
        
        private string dataInicioAnaliseViabilidadeField;
        
        private string horaInicioAnaliseViabilidadeField;
        
        private string dataFimAnaliseViabilidadeNomeField;
        
        private string horaFimAnaliseViabilidadeNomeField;
        
        private string dataFimAnaliseViabilidadeEnderecoField;
        
        private string horaFimAnaliseViabilidadeEnderecoField;
        
        private string cpfSolicitanteField;
        
        private string cnpjField;
        
        private string cnpjFilialField;
        
        private string indicadorCnpjNomeEmpresarialField;
        
        private string nomeEmpresarialField;
        
        private string areaImovelField;
        
        private string areaEstabelecimentoField;
        
        private string inscricaoImovelField;
        
        private string tipoInscricaoField;
        
        private string ufField;
        
        private string codMunicipioField;
        
        private string codTipoLogradouroField;
        
        private string logradouroField;
        
        private string numLogradouroField;
        
        private complementoLogradouro[] complementoLogradouroField;
        
        private string bairroField;
        
        private string distritoField;
        
        private string cepField;
        
        private string referenciaField;
        
        private Cnae cnaePrincipalField;
        
        private Cnae[] cnaeSecundariaField;
        
        private string[] tipoUnidadeField;
        
        private string[] formaAtuacaoField;
        
        private string objetoSocialField;
        
        private string tipoOrgaoRegistroField;
        
        private string naturezaJuridicaField;
        
        private string indicadorContabilistaField;
        
        private string[] nomeSocioPfField;
        
        private string[] cpfSocioPfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codServico {
            get {
                return this.codServicoField;
            }
            set {
                this.codServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usoRFB {
            get {
                return this.usoRFBField;
            }
            set {
                this.usoRFBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codEventosViabilidade", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] codEventosViabilidade {
            get {
                return this.codEventosViabilidadeField;
            }
            set {
                this.codEventosViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codStatusViabilidade {
            get {
                return this.codStatusViabilidadeField;
            }
            set {
                this.codStatusViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string protocoloViabilidade {
            get {
                return this.protocoloViabilidadeField;
            }
            set {
                this.protocoloViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string protocoloRLE {
            get {
                return this.protocoloRLEField;
            }
            set {
                this.protocoloRLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataValidadeViabilidade {
            get {
                return this.dataValidadeViabilidadeField;
            }
            set {
                this.dataValidadeViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultadoViabilidadeNome {
            get {
                return this.resultadoViabilidadeNomeField;
            }
            set {
                this.resultadoViabilidadeNomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultadoViabilidadeEndereco {
            get {
                return this.resultadoViabilidadeEnderecoField;
            }
            set {
                this.resultadoViabilidadeEnderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataInicioAnaliseViabilidade {
            get {
                return this.dataInicioAnaliseViabilidadeField;
            }
            set {
                this.dataInicioAnaliseViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string horaInicioAnaliseViabilidade {
            get {
                return this.horaInicioAnaliseViabilidadeField;
            }
            set {
                this.horaInicioAnaliseViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataFimAnaliseViabilidadeNome {
            get {
                return this.dataFimAnaliseViabilidadeNomeField;
            }
            set {
                this.dataFimAnaliseViabilidadeNomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string horaFimAnaliseViabilidadeNome {
            get {
                return this.horaFimAnaliseViabilidadeNomeField;
            }
            set {
                this.horaFimAnaliseViabilidadeNomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataFimAnaliseViabilidadeEndereco {
            get {
                return this.dataFimAnaliseViabilidadeEnderecoField;
            }
            set {
                this.dataFimAnaliseViabilidadeEnderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string horaFimAnaliseViabilidadeEndereco {
            get {
                return this.horaFimAnaliseViabilidadeEnderecoField;
            }
            set {
                this.horaFimAnaliseViabilidadeEnderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfSolicitante {
            get {
                return this.cpfSolicitanteField;
            }
            set {
                this.cpfSolicitanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpjFilial {
            get {
                return this.cnpjFilialField;
            }
            set {
                this.cnpjFilialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indicadorCnpjNomeEmpresarial {
            get {
                return this.indicadorCnpjNomeEmpresarialField;
            }
            set {
                this.indicadorCnpjNomeEmpresarialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeEmpresarial {
            get {
                return this.nomeEmpresarialField;
            }
            set {
                this.nomeEmpresarialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaImovel {
            get {
                return this.areaImovelField;
            }
            set {
                this.areaImovelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaEstabelecimento {
            get {
                return this.areaEstabelecimentoField;
            }
            set {
                this.areaEstabelecimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inscricaoImovel {
            get {
                return this.inscricaoImovelField;
            }
            set {
                this.inscricaoImovelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoInscricao {
            get {
                return this.tipoInscricaoField;
            }
            set {
                this.tipoInscricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codMunicipio {
            get {
                return this.codMunicipioField;
            }
            set {
                this.codMunicipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoLogradouro {
            get {
                return this.codTipoLogradouroField;
            }
            set {
                this.codTipoLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numLogradouro {
            get {
                return this.numLogradouroField;
            }
            set {
                this.numLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("complementoLogradouro", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public complementoLogradouro[] complementoLogradouro {
            get {
                return this.complementoLogradouroField;
            }
            set {
                this.complementoLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Cnae cnaePrincipal {
            get {
                return this.cnaePrincipalField;
            }
            set {
                this.cnaePrincipalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cnaeSecundaria", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Cnae[] cnaeSecundaria {
            get {
                return this.cnaeSecundariaField;
            }
            set {
                this.cnaeSecundariaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tipoUnidade", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] tipoUnidade {
            get {
                return this.tipoUnidadeField;
            }
            set {
                this.tipoUnidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("formaAtuacao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] formaAtuacao {
            get {
                return this.formaAtuacaoField;
            }
            set {
                this.formaAtuacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string objetoSocial {
            get {
                return this.objetoSocialField;
            }
            set {
                this.objetoSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoOrgaoRegistro {
            get {
                return this.tipoOrgaoRegistroField;
            }
            set {
                this.tipoOrgaoRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string naturezaJuridica {
            get {
                return this.naturezaJuridicaField;
            }
            set {
                this.naturezaJuridicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indicadorContabilista {
            get {
                return this.indicadorContabilistaField;
            }
            set {
                this.indicadorContabilistaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nomeSocioPf", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] nomeSocioPf {
            get {
                return this.nomeSocioPfField;
            }
            set {
                this.nomeSocioPfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cpfSocioPf", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] cpfSocioPf {
            get {
                return this.cpfSocioPfField;
            }
            set {
                this.cpfSocioPfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class complementoLogradouro {
        
        private string tipoComplementoLogradouroField;
        
        private string descricaoComplementoLogradouroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoComplementoLogradouro {
            get {
                return this.tipoComplementoLogradouroField;
            }
            set {
                this.tipoComplementoLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoComplementoLogradouro {
            get {
                return this.descricaoComplementoLogradouroField;
            }
            set {
                this.descricaoComplementoLogradouroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class mensagemRetorno {
        
        private string codigoRetornoField;
        
        private string descricaoRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoRetorno {
            get {
                return this.descricaoRetornoField;
            }
            set {
                this.descricaoRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class retornoWSRedesim {
        
        private string statusEnvioField;
        
        private string codigoRetornoField;
        
        private string descricaoRetornoField;
        
        private mensagemRetorno[] mensagemRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string statusEnvio {
            get {
                return this.statusEnvioField;
            }
            set {
                this.statusEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoRetorno {
            get {
                return this.descricaoRetornoField;
            }
            set {
                this.descricaoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensagemRetorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mensagemRetorno[] mensagemRetorno {
            get {
                return this.mensagemRetornoField;
            }
            set {
                this.mensagemRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class processarViabilidadeResponse {
        
        private retornoWSRedesim retornoWSRedesimField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public retornoWSRedesim retornoWSRedesim {
            get {
                return this.retornoWSRedesimField;
            }
            set {
                this.retornoWSRedesimField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class Cnae {
        
        private string codigoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void processarViabilidadeCompletedEventHandler(object sender, processarViabilidadeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processarViabilidadeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processarViabilidadeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public processarViabilidadeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((processarViabilidadeResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591