//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WsRFBReginV2.WsServices02RFB {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS02HttpSoapBinding", Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class WS02Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback alterarStatusViabilidadeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS02Service() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::WsRFBReginV2.Properties.Settings.Default.WsRFBReginV2_WsServices02RFB_WS02Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event alterarStatusViabilidadeCompletedEventHandler alterarStatusViabilidadeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("/WS02Service.serviceagent/WS02HttpSoap/alterarStatusViabilidade", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("alterarStatusViabilidadeResponse", Namespace="http://servicos.integrador.serpro.gov.br/")]
        public alterarStatusViabilidadeResponse alterarStatusViabilidade([System.Xml.Serialization.XmlElementAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")] alterarStatusViabilidadeRequest alterarStatusViabilidadeRequest) {
            object[] results = this.Invoke("alterarStatusViabilidade", new object[] {
                        alterarStatusViabilidadeRequest});
            return ((alterarStatusViabilidadeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void alterarStatusViabilidadeAsync(alterarStatusViabilidadeRequest alterarStatusViabilidadeRequest) {
            this.alterarStatusViabilidadeAsync(alterarStatusViabilidadeRequest, null);
        }
        
        /// <remarks/>
        public void alterarStatusViabilidadeAsync(alterarStatusViabilidadeRequest alterarStatusViabilidadeRequest, object userState) {
            if ((this.alterarStatusViabilidadeOperationCompleted == null)) {
                this.alterarStatusViabilidadeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalterarStatusViabilidadeOperationCompleted);
            }
            this.InvokeAsync("alterarStatusViabilidade", new object[] {
                        alterarStatusViabilidadeRequest}, this.alterarStatusViabilidadeOperationCompleted, userState);
        }
        
        private void OnalterarStatusViabilidadeOperationCompleted(object arg) {
            if ((this.alterarStatusViabilidadeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alterarStatusViabilidadeCompleted(this, new alterarStatusViabilidadeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class alterarStatusViabilidadeRequest {
        
        private string codServicoField;
        
        private string usoRFBField;
        
        private string codStatusViabilidadeField;
        
        private string protocoloViabilidadeField;
        
        private string dataValidadeViabilidadeField;
        
        private string resultadoViabilidadeNomeField;
        
        private string resultadoViabilidadeEnderecoField;
        
        private string dataInicioAnaliseViabilidadeField;
        
        private string dataFimAnaliseViabilidadeNomeField;
        
        private string dataFimAnaliseViabilidadeEnderecoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codServico {
            get {
                return this.codServicoField;
            }
            set {
                this.codServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usoRFB {
            get {
                return this.usoRFBField;
            }
            set {
                this.usoRFBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codStatusViabilidade {
            get {
                return this.codStatusViabilidadeField;
            }
            set {
                this.codStatusViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string protocoloViabilidade {
            get {
                return this.protocoloViabilidadeField;
            }
            set {
                this.protocoloViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataValidadeViabilidade {
            get {
                return this.dataValidadeViabilidadeField;
            }
            set {
                this.dataValidadeViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultadoViabilidadeNome {
            get {
                return this.resultadoViabilidadeNomeField;
            }
            set {
                this.resultadoViabilidadeNomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultadoViabilidadeEndereco {
            get {
                return this.resultadoViabilidadeEnderecoField;
            }
            set {
                this.resultadoViabilidadeEnderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataInicioAnaliseViabilidade {
            get {
                return this.dataInicioAnaliseViabilidadeField;
            }
            set {
                this.dataInicioAnaliseViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataFimAnaliseViabilidadeNome {
            get {
                return this.dataFimAnaliseViabilidadeNomeField;
            }
            set {
                this.dataFimAnaliseViabilidadeNomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataFimAnaliseViabilidadeEndereco {
            get {
                return this.dataFimAnaliseViabilidadeEnderecoField;
            }
            set {
                this.dataFimAnaliseViabilidadeEnderecoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class mensagemRetorno {
        
        private string codigoRetornoField;
        
        private string descricaoRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoRetorno {
            get {
                return this.descricaoRetornoField;
            }
            set {
                this.descricaoRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class retornoWSRedesim {
        
        private string statusEnvioField;
        
        private string codigoRetornoField;
        
        private string descricaoRetornoField;
        
        private mensagemRetorno[] mensagemRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string statusEnvio {
            get {
                return this.statusEnvioField;
            }
            set {
                this.statusEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoRetorno {
            get {
                return this.descricaoRetornoField;
            }
            set {
                this.descricaoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensagemRetorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mensagemRetorno[] mensagemRetorno {
            get {
                return this.mensagemRetornoField;
            }
            set {
                this.mensagemRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.integrador.serpro.gov.br/")]
    public partial class alterarStatusViabilidadeResponse {
        
        private retornoWSRedesim retornoWSRedesimField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public retornoWSRedesim retornoWSRedesim {
            get {
                return this.retornoWSRedesimField;
            }
            set {
                this.retornoWSRedesimField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void alterarStatusViabilidadeCompletedEventHandler(object sender, alterarStatusViabilidadeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class alterarStatusViabilidadeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal alterarStatusViabilidadeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public alterarStatusViabilidadeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((alterarStatusViabilidadeResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591