//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WsRFBReginV2.WsServices35RFB {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ws35SoapBinding", Namespace="http://redesim.serpro.gov.br/")]
    public partial class ws35 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback buscarOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ws35() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::WsRFBReginV2.Properties.Settings.Default.WsRFBReginV2_WsServices35RFB_ws35;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event buscarCompletedEventHandler buscarCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("serviceResponse", Namespace="http://redesim.serpro.gov.br/")]
        public serviceResponse buscar([System.Xml.Serialization.XmlElementAttribute(Namespace="http://redesim.serpro.gov.br/")] serviceRequest serviceRequest) {
            object[] results = this.Invoke("buscar", new object[] {
                        serviceRequest});
            return ((serviceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void buscarAsync(serviceRequest serviceRequest) {
            this.buscarAsync(serviceRequest, null);
        }
        
        /// <remarks/>
        public void buscarAsync(serviceRequest serviceRequest, object userState) {
            if ((this.buscarOperationCompleted == null)) {
                this.buscarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarOperationCompleted);
            }
            this.InvokeAsync("buscar", new object[] {
                        serviceRequest}, this.buscarOperationCompleted, userState);
        }
        
        private void OnbuscarOperationCompleted(object arg) {
            if ((this.buscarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarCompleted(this, new buscarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class serviceRequest {
        
        private string codServicoField;
        
        private string versaoField;
        
        private string reciboSolicitacaoField;
        
        private string identificacaoSolicitacaoField;
        
        private string usoRFBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codServico {
            get {
                return this.codServicoField;
            }
            set {
                this.codServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reciboSolicitacao {
            get {
                return this.reciboSolicitacaoField;
            }
            set {
                this.reciboSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacaoSolicitacao {
            get {
                return this.identificacaoSolicitacaoField;
            }
            set {
                this.identificacaoSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usoRFB {
            get {
                return this.usoRFBField;
            }
            set {
                this.usoRFBField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class socio {
        
        private string indTipoContribuinteField;
        
        private string codEventoField;
        
        private string dataEventoField;
        
        private string indCnpjCpfSocioField;
        
        private string cnpjCpfSocioField;
        
        private string socio1Field;
        
        private string capitalSocialSocioField;
        
        private string codQualificacaoSocioField;
        
        private string codPaisField;
        
        private string nacionalidadeSocioPfField;
        
        private string dataInclusaoIncorretaField;
        
        private string dataInclusaoCorretaField;
        
        private endereco endSocioField;
        
        private contato contatoSocioField;
        
        private string representanteLegalField;
        
        private string codQualificacaoRepresentanteLegalField;
        
        private string cpfRepresentanteLegalField;
        
        private endereco endRepLegalField;
        
        private contato contatoRepLegalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indTipoContribuinte {
            get {
                return this.indTipoContribuinteField;
            }
            set {
                this.indTipoContribuinteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codEvento {
            get {
                return this.codEventoField;
            }
            set {
                this.codEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataEvento {
            get {
                return this.dataEventoField;
            }
            set {
                this.dataEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indCnpjCpfSocio {
            get {
                return this.indCnpjCpfSocioField;
            }
            set {
                this.indCnpjCpfSocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpjCpfSocio {
            get {
                return this.cnpjCpfSocioField;
            }
            set {
                this.cnpjCpfSocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("socio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string socio1 {
            get {
                return this.socio1Field;
            }
            set {
                this.socio1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string capitalSocialSocio {
            get {
                return this.capitalSocialSocioField;
            }
            set {
                this.capitalSocialSocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codQualificacaoSocio {
            get {
                return this.codQualificacaoSocioField;
            }
            set {
                this.codQualificacaoSocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPais {
            get {
                return this.codPaisField;
            }
            set {
                this.codPaisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nacionalidadeSocioPf {
            get {
                return this.nacionalidadeSocioPfField;
            }
            set {
                this.nacionalidadeSocioPfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataInclusaoIncorreta {
            get {
                return this.dataInclusaoIncorretaField;
            }
            set {
                this.dataInclusaoIncorretaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataInclusaoCorreta {
            get {
                return this.dataInclusaoCorretaField;
            }
            set {
                this.dataInclusaoCorretaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco endSocio {
            get {
                return this.endSocioField;
            }
            set {
                this.endSocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contato contatoSocio {
            get {
                return this.contatoSocioField;
            }
            set {
                this.contatoSocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string representanteLegal {
            get {
                return this.representanteLegalField;
            }
            set {
                this.representanteLegalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codQualificacaoRepresentanteLegal {
            get {
                return this.codQualificacaoRepresentanteLegalField;
            }
            set {
                this.codQualificacaoRepresentanteLegalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfRepresentanteLegal {
            get {
                return this.cpfRepresentanteLegalField;
            }
            set {
                this.cpfRepresentanteLegalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco endRepLegal {
            get {
                return this.endRepLegalField;
            }
            set {
                this.endRepLegalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contato contatoRepLegal {
            get {
                return this.contatoRepLegalField;
            }
            set {
                this.contatoRepLegalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class endereco {
        
        private string indOrigemEnderecoField;
        
        private string cepField;
        
        private string ufField;
        
        private string codMunicipioField;
        
        private string codTipoLogradouroField;
        
        private string logradouroField;
        
        private string numLogradouroField;
        
        private string complementoLogradouroField;
        
        private string bairroField;
        
        private string distritoField;
        
        private string referenciaField;
        
        private string cidadeExteriorField;
        
        private string codPaisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indOrigemEndereco {
            get {
                return this.indOrigemEnderecoField;
            }
            set {
                this.indOrigemEnderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codMunicipio {
            get {
                return this.codMunicipioField;
            }
            set {
                this.codMunicipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoLogradouro {
            get {
                return this.codTipoLogradouroField;
            }
            set {
                this.codTipoLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numLogradouro {
            get {
                return this.numLogradouroField;
            }
            set {
                this.numLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string complementoLogradouro {
            get {
                return this.complementoLogradouroField;
            }
            set {
                this.complementoLogradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cidadeExterior {
            get {
                return this.cidadeExteriorField;
            }
            set {
                this.cidadeExteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPais {
            get {
                return this.codPaisField;
            }
            set {
                this.codPaisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class contato {
        
        private string dddTelefone1Field;
        
        private string telefone1Field;
        
        private string dddTelefone2Field;
        
        private string telefone2Field;
        
        private string dddFaxField;
        
        private string faxField;
        
        private string correioEletronicoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dddTelefone1 {
            get {
                return this.dddTelefone1Field;
            }
            set {
                this.dddTelefone1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefone1 {
            get {
                return this.telefone1Field;
            }
            set {
                this.telefone1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dddTelefone2 {
            get {
                return this.dddTelefone2Field;
            }
            set {
                this.dddTelefone2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefone2 {
            get {
                return this.telefone2Field;
            }
            set {
                this.telefone2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dddFax {
            get {
                return this.dddFaxField;
            }
            set {
                this.dddFaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correioEletronico {
            get {
                return this.correioEletronicoField;
            }
            set {
                this.correioEletronicoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class fcpj {
        
        private string[] codEventoField;
        
        private string[] dataEventoField;
        
        private string[] tipoEventoField;
        
        private string inMatrizField;
        
        private string indicadorCnpjNomeEmpresarialField;
        
        private string nomeEmpresarialField;
        
        private string nomeFantasiaField;
        
        private string codNaturezaJuridicaField;
        
        private string codTipoOrgaoRegistroField;
        
        private string nireField;
        
        private string numeroRegistroCartorioField;
        
        private string numeroDoCNPJOrgaoRegistroField;
        
        private string arquivamentoField;
        
        private string capitalSocialField;
        
        private string cnpjEstabMatrizField;
        
        private string codEnteFederativoField;
        
        private string nomeResponsavelField;
        
        private string cpfResponsavelField;
        
        private string codQualificResponsavelField;
        
        private string nomePrepostoField;
        
        private string cpfPrepostoField;
        
        private string ufOrigemField;
        
        private string codMunicOrigemField;
        
        private endereco enderecoField;
        
        private contato contatoField;
        
        private endereco enderecoCorrespondenciaField;
        
        private string caixaPostalField;
        
        private string cepCaixaPostalField;
        
        private string codPorteEmpresaField;
        
        private string[] cnpjSucessoraField;
        
        private string codClassificCRCcontadorPFField;
        
        private string ufContadorPFField;
        
        private string numSeqContadorPFField;
        
        private string codTipoCRCcontadorPFField;
        
        private string cpfContadorPFField;
        
        private string nomeContadorPFField;
        
        private string dataRegistroCRCcontadorPFField;
        
        private string idContadorPFField;
        
        private string orgaoEmissorIdContadorPFField;
        
        private string ufOrgaoEmissorIdContadorPFField;
        
        private string dataEmissaoIdContadorPFField;
        
        private string codClassificEmpresaContabilField;
        
        private string ufCRCempresaContabilField;
        
        private string seqCRCempresaContabilField;
        
        private string codTipoCRCempresaContabilField;
        
        private string cnpjEmpresaContabilField;
        
        private string nomeEmpresaContabilField;
        
        private string inPermanencialivrosFiscaisField;
        
        private string inOpcaoLivrosEletronicosField;
        
        private string inOpcaoDocumentosEletronicosField;
        
        private string inProcessamentoEletronicoDadosField;
        
        private string inUtilizacaoECFField;
        
        private string codVinculoImovelField;
        
        private string dataValidadeInscricaoField;
        
        private string nirfField;
        
        private string nomeProprietarioRuralField;
        
        private string inCpfCnpjProprietarioField;
        
        private string cpfCnpjProprietarioRuralField;
        
        private string inscricaoEstadualAnteriorProdutorRuralField;
        
        private string codLocalizacaoImovelField;
        
        private string numIncraProprietarioField;
        
        private string inscricaoImobiliariaImovelRuralField;
        
        private string areaImovelField;
        
        private string inAbrangenciaMunicField;
        
        private string codMotivoSituacaoCadastralField;
        
        private string dataDocumentoInaptidaoField;
        
        private string numDocumentoInaptidaoField;
        
        private endereco endResponsavelField;
        
        private contato contatoResponsavelField;
        
        private endereco endPrepostoField;
        
        private contato contatoPrepostoField;
        
        private endereco endContadorPfField;
        
        private contato contatoContadorPfField;
        
        private endereco endProprietarioRuralPfField;
        
        private contato contatoProprietarioRuralPfField;
        
        private endereco endEmpresaContabilComplementarField;
        
        private contato contatoEmpresaContabilComplementarField;
        
        private string inCpfCnpjProprietarioCafirField;
        
        private string cpfCnpjProprietarioCafirField;
        
        private string codSitCadProprietarioComplementarField;
        
        private string codMotivoSitCadProprietarioComplementarField;
        
        private string areaImovelComplementarField;
        
        private string nomeImovelComplementarField;
        
        private endereco endProprietarioComplementarField;
        
        private contato contatoProprietarioComplementarField;
        
        private string instrumentoJudicialField;
        
        private string inOpcaoSimplesField;
        
        private string tipoEstatalField;
        
        private string inInscricaoMEIField;
        
        private string nire246Field;
        
        private string motivoInexistenciaRegistroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codEvento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] codEvento {
            get {
                return this.codEventoField;
            }
            set {
                this.codEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dataEvento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] dataEvento {
            get {
                return this.dataEventoField;
            }
            set {
                this.dataEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tipoEvento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] tipoEvento {
            get {
                return this.tipoEventoField;
            }
            set {
                this.tipoEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inMatriz {
            get {
                return this.inMatrizField;
            }
            set {
                this.inMatrizField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indicadorCnpjNomeEmpresarial {
            get {
                return this.indicadorCnpjNomeEmpresarialField;
            }
            set {
                this.indicadorCnpjNomeEmpresarialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeEmpresarial {
            get {
                return this.nomeEmpresarialField;
            }
            set {
                this.nomeEmpresarialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeFantasia {
            get {
                return this.nomeFantasiaField;
            }
            set {
                this.nomeFantasiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codNaturezaJuridica {
            get {
                return this.codNaturezaJuridicaField;
            }
            set {
                this.codNaturezaJuridicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoOrgaoRegistro {
            get {
                return this.codTipoOrgaoRegistroField;
            }
            set {
                this.codTipoOrgaoRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nire {
            get {
                return this.nireField;
            }
            set {
                this.nireField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroRegistroCartorio {
            get {
                return this.numeroRegistroCartorioField;
            }
            set {
                this.numeroRegistroCartorioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroDoCNPJOrgaoRegistro {
            get {
                return this.numeroDoCNPJOrgaoRegistroField;
            }
            set {
                this.numeroDoCNPJOrgaoRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arquivamento {
            get {
                return this.arquivamentoField;
            }
            set {
                this.arquivamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string capitalSocial {
            get {
                return this.capitalSocialField;
            }
            set {
                this.capitalSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpjEstabMatriz {
            get {
                return this.cnpjEstabMatrizField;
            }
            set {
                this.cnpjEstabMatrizField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codEnteFederativo {
            get {
                return this.codEnteFederativoField;
            }
            set {
                this.codEnteFederativoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeResponsavel {
            get {
                return this.nomeResponsavelField;
            }
            set {
                this.nomeResponsavelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfResponsavel {
            get {
                return this.cpfResponsavelField;
            }
            set {
                this.cpfResponsavelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codQualificResponsavel {
            get {
                return this.codQualificResponsavelField;
            }
            set {
                this.codQualificResponsavelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomePreposto {
            get {
                return this.nomePrepostoField;
            }
            set {
                this.nomePrepostoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfPreposto {
            get {
                return this.cpfPrepostoField;
            }
            set {
                this.cpfPrepostoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ufOrigem {
            get {
                return this.ufOrigemField;
            }
            set {
                this.ufOrigemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codMunicOrigem {
            get {
                return this.codMunicOrigemField;
            }
            set {
                this.codMunicOrigemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contato contato {
            get {
                return this.contatoField;
            }
            set {
                this.contatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco enderecoCorrespondencia {
            get {
                return this.enderecoCorrespondenciaField;
            }
            set {
                this.enderecoCorrespondenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string caixaPostal {
            get {
                return this.caixaPostalField;
            }
            set {
                this.caixaPostalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cepCaixaPostal {
            get {
                return this.cepCaixaPostalField;
            }
            set {
                this.cepCaixaPostalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPorteEmpresa {
            get {
                return this.codPorteEmpresaField;
            }
            set {
                this.codPorteEmpresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cnpjSucessora", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] cnpjSucessora {
            get {
                return this.cnpjSucessoraField;
            }
            set {
                this.cnpjSucessoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codClassificCRCcontadorPF {
            get {
                return this.codClassificCRCcontadorPFField;
            }
            set {
                this.codClassificCRCcontadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ufContadorPF {
            get {
                return this.ufContadorPFField;
            }
            set {
                this.ufContadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numSeqContadorPF {
            get {
                return this.numSeqContadorPFField;
            }
            set {
                this.numSeqContadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoCRCcontadorPF {
            get {
                return this.codTipoCRCcontadorPFField;
            }
            set {
                this.codTipoCRCcontadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfContadorPF {
            get {
                return this.cpfContadorPFField;
            }
            set {
                this.cpfContadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeContadorPF {
            get {
                return this.nomeContadorPFField;
            }
            set {
                this.nomeContadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataRegistroCRCcontadorPF {
            get {
                return this.dataRegistroCRCcontadorPFField;
            }
            set {
                this.dataRegistroCRCcontadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idContadorPF {
            get {
                return this.idContadorPFField;
            }
            set {
                this.idContadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orgaoEmissorIdContadorPF {
            get {
                return this.orgaoEmissorIdContadorPFField;
            }
            set {
                this.orgaoEmissorIdContadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ufOrgaoEmissorIdContadorPF {
            get {
                return this.ufOrgaoEmissorIdContadorPFField;
            }
            set {
                this.ufOrgaoEmissorIdContadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataEmissaoIdContadorPF {
            get {
                return this.dataEmissaoIdContadorPFField;
            }
            set {
                this.dataEmissaoIdContadorPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codClassificEmpresaContabil {
            get {
                return this.codClassificEmpresaContabilField;
            }
            set {
                this.codClassificEmpresaContabilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ufCRCempresaContabil {
            get {
                return this.ufCRCempresaContabilField;
            }
            set {
                this.ufCRCempresaContabilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string seqCRCempresaContabil {
            get {
                return this.seqCRCempresaContabilField;
            }
            set {
                this.seqCRCempresaContabilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoCRCempresaContabil {
            get {
                return this.codTipoCRCempresaContabilField;
            }
            set {
                this.codTipoCRCempresaContabilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpjEmpresaContabil {
            get {
                return this.cnpjEmpresaContabilField;
            }
            set {
                this.cnpjEmpresaContabilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeEmpresaContabil {
            get {
                return this.nomeEmpresaContabilField;
            }
            set {
                this.nomeEmpresaContabilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inPermanencialivrosFiscais {
            get {
                return this.inPermanencialivrosFiscaisField;
            }
            set {
                this.inPermanencialivrosFiscaisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inOpcaoLivrosEletronicos {
            get {
                return this.inOpcaoLivrosEletronicosField;
            }
            set {
                this.inOpcaoLivrosEletronicosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inOpcaoDocumentosEletronicos {
            get {
                return this.inOpcaoDocumentosEletronicosField;
            }
            set {
                this.inOpcaoDocumentosEletronicosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inProcessamentoEletronicoDados {
            get {
                return this.inProcessamentoEletronicoDadosField;
            }
            set {
                this.inProcessamentoEletronicoDadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inUtilizacaoECF {
            get {
                return this.inUtilizacaoECFField;
            }
            set {
                this.inUtilizacaoECFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codVinculoImovel {
            get {
                return this.codVinculoImovelField;
            }
            set {
                this.codVinculoImovelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataValidadeInscricao {
            get {
                return this.dataValidadeInscricaoField;
            }
            set {
                this.dataValidadeInscricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nirf {
            get {
                return this.nirfField;
            }
            set {
                this.nirfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeProprietarioRural {
            get {
                return this.nomeProprietarioRuralField;
            }
            set {
                this.nomeProprietarioRuralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inCpfCnpjProprietario {
            get {
                return this.inCpfCnpjProprietarioField;
            }
            set {
                this.inCpfCnpjProprietarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfCnpjProprietarioRural {
            get {
                return this.cpfCnpjProprietarioRuralField;
            }
            set {
                this.cpfCnpjProprietarioRuralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inscricaoEstadualAnteriorProdutorRural {
            get {
                return this.inscricaoEstadualAnteriorProdutorRuralField;
            }
            set {
                this.inscricaoEstadualAnteriorProdutorRuralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codLocalizacaoImovel {
            get {
                return this.codLocalizacaoImovelField;
            }
            set {
                this.codLocalizacaoImovelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numIncraProprietario {
            get {
                return this.numIncraProprietarioField;
            }
            set {
                this.numIncraProprietarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inscricaoImobiliariaImovelRural {
            get {
                return this.inscricaoImobiliariaImovelRuralField;
            }
            set {
                this.inscricaoImobiliariaImovelRuralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaImovel {
            get {
                return this.areaImovelField;
            }
            set {
                this.areaImovelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inAbrangenciaMunic {
            get {
                return this.inAbrangenciaMunicField;
            }
            set {
                this.inAbrangenciaMunicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codMotivoSituacaoCadastral {
            get {
                return this.codMotivoSituacaoCadastralField;
            }
            set {
                this.codMotivoSituacaoCadastralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataDocumentoInaptidao {
            get {
                return this.dataDocumentoInaptidaoField;
            }
            set {
                this.dataDocumentoInaptidaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numDocumentoInaptidao {
            get {
                return this.numDocumentoInaptidaoField;
            }
            set {
                this.numDocumentoInaptidaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco endResponsavel {
            get {
                return this.endResponsavelField;
            }
            set {
                this.endResponsavelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contato contatoResponsavel {
            get {
                return this.contatoResponsavelField;
            }
            set {
                this.contatoResponsavelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco endPreposto {
            get {
                return this.endPrepostoField;
            }
            set {
                this.endPrepostoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contato contatoPreposto {
            get {
                return this.contatoPrepostoField;
            }
            set {
                this.contatoPrepostoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco endContadorPf {
            get {
                return this.endContadorPfField;
            }
            set {
                this.endContadorPfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contato contatoContadorPf {
            get {
                return this.contatoContadorPfField;
            }
            set {
                this.contatoContadorPfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco endProprietarioRuralPf {
            get {
                return this.endProprietarioRuralPfField;
            }
            set {
                this.endProprietarioRuralPfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contato contatoProprietarioRuralPf {
            get {
                return this.contatoProprietarioRuralPfField;
            }
            set {
                this.contatoProprietarioRuralPfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco endEmpresaContabilComplementar {
            get {
                return this.endEmpresaContabilComplementarField;
            }
            set {
                this.endEmpresaContabilComplementarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contato contatoEmpresaContabilComplementar {
            get {
                return this.contatoEmpresaContabilComplementarField;
            }
            set {
                this.contatoEmpresaContabilComplementarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inCpfCnpjProprietarioCafir {
            get {
                return this.inCpfCnpjProprietarioCafirField;
            }
            set {
                this.inCpfCnpjProprietarioCafirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfCnpjProprietarioCafir {
            get {
                return this.cpfCnpjProprietarioCafirField;
            }
            set {
                this.cpfCnpjProprietarioCafirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codSitCadProprietarioComplementar {
            get {
                return this.codSitCadProprietarioComplementarField;
            }
            set {
                this.codSitCadProprietarioComplementarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codMotivoSitCadProprietarioComplementar {
            get {
                return this.codMotivoSitCadProprietarioComplementarField;
            }
            set {
                this.codMotivoSitCadProprietarioComplementarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaImovelComplementar {
            get {
                return this.areaImovelComplementarField;
            }
            set {
                this.areaImovelComplementarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeImovelComplementar {
            get {
                return this.nomeImovelComplementarField;
            }
            set {
                this.nomeImovelComplementarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco endProprietarioComplementar {
            get {
                return this.endProprietarioComplementarField;
            }
            set {
                this.endProprietarioComplementarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contato contatoProprietarioComplementar {
            get {
                return this.contatoProprietarioComplementarField;
            }
            set {
                this.contatoProprietarioComplementarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string instrumentoJudicial {
            get {
                return this.instrumentoJudicialField;
            }
            set {
                this.instrumentoJudicialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inOpcaoSimples {
            get {
                return this.inOpcaoSimplesField;
            }
            set {
                this.inOpcaoSimplesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoEstatal {
            get {
                return this.tipoEstatalField;
            }
            set {
                this.tipoEstatalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inInscricaoMEI {
            get {
                return this.inInscricaoMEIField;
            }
            set {
                this.inInscricaoMEIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nire246 {
            get {
                return this.nire246Field;
            }
            set {
                this.nire246Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string motivoInexistenciaRegistro {
            get {
                return this.motivoInexistenciaRegistroField;
            }
            set {
                this.motivoInexistenciaRegistroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class ativEcon {
        
        private string codCnaeFiscalField;
        
        private string[] codCnaeSecundariaField;
        
        private string[] codFormaDeAtuacaoField;
        
        private string[] codTipoUnidadeField;
        
        private string objetoSocialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codCnaeFiscal {
            get {
                return this.codCnaeFiscalField;
            }
            set {
                this.codCnaeFiscalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codCnaeSecundaria", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] codCnaeSecundaria {
            get {
                return this.codCnaeSecundariaField;
            }
            set {
                this.codCnaeSecundariaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codFormaDeAtuacao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] codFormaDeAtuacao {
            get {
                return this.codFormaDeAtuacaoField;
            }
            set {
                this.codFormaDeAtuacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codTipoUnidade", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] codTipoUnidade {
            get {
                return this.codTipoUnidadeField;
            }
            set {
                this.codTipoUnidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string objetoSocial {
            get {
                return this.objetoSocialField;
            }
            set {
                this.objetoSocialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class viabilidade {
        
        private string[] codEventosViabilidadeField;
        
        private string codStatusViabilidadeField;
        
        private string protocoloViabilidadeField;
        
        private string protocoloRLEField;
        
        private string dataValidadeViabilidadeField;
        
        private string resultadoViabilidadeNomeField;
        
        private string resultadoViabilidadeEnderecoField;
        
        private string dataInicioAnaliseViabilidadeField;
        
        private string dataFimAnaliseViabilidadeNomeField;
        
        private string dataFimAnaliseViabilidadeEnderecoField;
        
        private string indicadorCnpjNomeEmpresarialField;
        
        private string nomeEmpresarialField;
        
        private string codNaturezaJuridicaField;
        
        private string codTipoOrgaoRegistroField;
        
        private string cnpjField;
        
        private string cnpjFilialField;
        
        private endereco enderecoField;
        
        private ativEcon atividadeEconomicaField;
        
        private string areaImovelField;
        
        private string areaEstabelecimentoField;
        
        private string inscricaoImovelField;
        
        private string tipoInscricaoField;
        
        private string indicadorContabilistaField;
        
        private string[] nomeSocioPfField;
        
        private string[] cpfSocioPfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codEventosViabilidade", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] codEventosViabilidade {
            get {
                return this.codEventosViabilidadeField;
            }
            set {
                this.codEventosViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codStatusViabilidade {
            get {
                return this.codStatusViabilidadeField;
            }
            set {
                this.codStatusViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string protocoloViabilidade {
            get {
                return this.protocoloViabilidadeField;
            }
            set {
                this.protocoloViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string protocoloRLE {
            get {
                return this.protocoloRLEField;
            }
            set {
                this.protocoloRLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataValidadeViabilidade {
            get {
                return this.dataValidadeViabilidadeField;
            }
            set {
                this.dataValidadeViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultadoViabilidadeNome {
            get {
                return this.resultadoViabilidadeNomeField;
            }
            set {
                this.resultadoViabilidadeNomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultadoViabilidadeEndereco {
            get {
                return this.resultadoViabilidadeEnderecoField;
            }
            set {
                this.resultadoViabilidadeEnderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataInicioAnaliseViabilidade {
            get {
                return this.dataInicioAnaliseViabilidadeField;
            }
            set {
                this.dataInicioAnaliseViabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataFimAnaliseViabilidadeNome {
            get {
                return this.dataFimAnaliseViabilidadeNomeField;
            }
            set {
                this.dataFimAnaliseViabilidadeNomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataFimAnaliseViabilidadeEndereco {
            get {
                return this.dataFimAnaliseViabilidadeEnderecoField;
            }
            set {
                this.dataFimAnaliseViabilidadeEnderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indicadorCnpjNomeEmpresarial {
            get {
                return this.indicadorCnpjNomeEmpresarialField;
            }
            set {
                this.indicadorCnpjNomeEmpresarialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeEmpresarial {
            get {
                return this.nomeEmpresarialField;
            }
            set {
                this.nomeEmpresarialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codNaturezaJuridica {
            get {
                return this.codNaturezaJuridicaField;
            }
            set {
                this.codNaturezaJuridicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoOrgaoRegistro {
            get {
                return this.codTipoOrgaoRegistroField;
            }
            set {
                this.codTipoOrgaoRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpjFilial {
            get {
                return this.cnpjFilialField;
            }
            set {
                this.cnpjFilialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public endereco endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ativEcon atividadeEconomica {
            get {
                return this.atividadeEconomicaField;
            }
            set {
                this.atividadeEconomicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaImovel {
            get {
                return this.areaImovelField;
            }
            set {
                this.areaImovelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaEstabelecimento {
            get {
                return this.areaEstabelecimentoField;
            }
            set {
                this.areaEstabelecimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inscricaoImovel {
            get {
                return this.inscricaoImovelField;
            }
            set {
                this.inscricaoImovelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoInscricao {
            get {
                return this.tipoInscricaoField;
            }
            set {
                this.tipoInscricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indicadorContabilista {
            get {
                return this.indicadorContabilistaField;
            }
            set {
                this.indicadorContabilistaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nomeSocioPf", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] nomeSocioPf {
            get {
                return this.nomeSocioPfField;
            }
            set {
                this.nomeSocioPfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cpfSocioPf", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] cpfSocioPf {
            get {
                return this.cpfSocioPfField;
            }
            set {
                this.cpfSocioPfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class header {
        
        private string inCpfCnpjCertificadoField;
        
        private string cpfCnpjCertificadoField;
        
        private string subjectCertificadoField;
        
        private string acCertificadoField;
        
        private string dataEmissaoCertificadoField;
        
        private string dataExpiracaoCertificadoField;
        
        private string numSerieCertificadoField;
        
        private string extensao1CertificadoField;
        
        private string extensao2CertificadoField;
        
        private string extensao3CertificadoField;
        
        private string cpfPreenchedorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inCpfCnpjCertificado {
            get {
                return this.inCpfCnpjCertificadoField;
            }
            set {
                this.inCpfCnpjCertificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfCnpjCertificado {
            get {
                return this.cpfCnpjCertificadoField;
            }
            set {
                this.cpfCnpjCertificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subjectCertificado {
            get {
                return this.subjectCertificadoField;
            }
            set {
                this.subjectCertificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acCertificado {
            get {
                return this.acCertificadoField;
            }
            set {
                this.acCertificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataEmissaoCertificado {
            get {
                return this.dataEmissaoCertificadoField;
            }
            set {
                this.dataEmissaoCertificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataExpiracaoCertificado {
            get {
                return this.dataExpiracaoCertificadoField;
            }
            set {
                this.dataExpiracaoCertificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numSerieCertificado {
            get {
                return this.numSerieCertificadoField;
            }
            set {
                this.numSerieCertificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extensao1Certificado {
            get {
                return this.extensao1CertificadoField;
            }
            set {
                this.extensao1CertificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extensao2Certificado {
            get {
                return this.extensao2CertificadoField;
            }
            set {
                this.extensao2CertificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extensao3Certificado {
            get {
                return this.extensao3CertificadoField;
            }
            set {
                this.extensao3CertificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfPreenchedor {
            get {
                return this.cpfPreenchedorField;
            }
            set {
                this.cpfPreenchedorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class redesim {
        
        private string convenioField;
        
        private string cnpjField;
        
        private string orgaoResponsavelDeferimentoField;
        
        private string numAtoOficioField;
        
        private string codConvenioAtoOficioField;
        
        private string numViabilidadeAssociadaField;
        
        private header headerField;
        
        private viabilidade viabilidadeField;
        
        private fcpj fcpjField;
        
        private ativEcon atividadeEconomicaField;
        
        private socio[] sociosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string convenio {
            get {
                return this.convenioField;
            }
            set {
                this.convenioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orgaoResponsavelDeferimento {
            get {
                return this.orgaoResponsavelDeferimentoField;
            }
            set {
                this.orgaoResponsavelDeferimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numAtoOficio {
            get {
                return this.numAtoOficioField;
            }
            set {
                this.numAtoOficioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codConvenioAtoOficio {
            get {
                return this.codConvenioAtoOficioField;
            }
            set {
                this.codConvenioAtoOficioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numViabilidadeAssociada {
            get {
                return this.numViabilidadeAssociadaField;
            }
            set {
                this.numViabilidadeAssociadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public header header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public viabilidade viabilidade {
            get {
                return this.viabilidadeField;
            }
            set {
                this.viabilidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public fcpj fcpj {
            get {
                return this.fcpjField;
            }
            set {
                this.fcpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ativEcon atividadeEconomica {
            get {
                return this.atividadeEconomicaField;
            }
            set {
                this.atividadeEconomicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("socios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public socio[] socios {
            get {
                return this.sociosField;
            }
            set {
                this.sociosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class bloqueioWS {
        
        private string codigoField;
        
        private string descricaoField;
        
        private string dataField;
        
        private string horaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class retornoWS {
        
        private string statusEnvioField;
        
        private string codigoRetornoField;
        
        private string descricaoRetornoField;
        
        private string numIdentificacaoTransmissaoField;
        
        private bloqueioWS cancelamentoDBEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string statusEnvio {
            get {
                return this.statusEnvioField;
            }
            set {
                this.statusEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoRetorno {
            get {
                return this.descricaoRetornoField;
            }
            set {
                this.descricaoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numIdentificacaoTransmissao {
            get {
                return this.numIdentificacaoTransmissaoField;
            }
            set {
                this.numIdentificacaoTransmissaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bloqueioWS cancelamentoDBE {
            get {
                return this.cancelamentoDBEField;
            }
            set {
                this.cancelamentoDBEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://redesim.serpro.gov.br/")]
    public partial class serviceResponse {
        
        private retornoWS returnField;
        
        private redesim dadosRedesimField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public retornoWS @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public redesim dadosRedesim {
            get {
                return this.dadosRedesimField;
            }
            set {
                this.dadosRedesimField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarCompletedEventHandler(object sender, buscarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public serviceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((serviceResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591